2023-01-13 22:10:19,672 INFO    ======================================================================
2023-01-13 22:10:19,673 INFO    Survey 7, for Ouro Preto
2023-01-13 22:10:19,674 INFO    Searching by bounding box, max_zoom=24
2023-01-13 22:10:19,675 INFO    ----------------------------------------------------------------------
2023-01-13 22:10:19,675 INFO    Rectangle calculated: [-20.2519, -43.4372, -20.5229, -43.7846]
2023-01-13 22:10:19,675 INFO    Searching rectangle: zoom factor = 0, node = []
2023-01-13 22:10:20,908 ERROR   Exception in get_search_page_info_rectangle
Traceback (most recent call last):
  File "C:\ufop\airbnb-data-collection\airbnb_listing.py", line 157, in save
    self.__insert()
  File "C:\ufop\airbnb-data-collection\airbnb_listing.py", line 328, in __insert
    cur.execute(sql, insert_args)
psycopg2.errors.NumericValueOutOfRange: integer out of range


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\ufop\airbnb-data-collection\airbnb_survey.py", line 781, in search_node
    if listing.save(self.config.FLAGS_INSERT_NO_REPLACE):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ufop\airbnb-data-collection\airbnb_listing.py", line 167, in save
    self.config.connection.conn.rollback()
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'psycopg2.extensions.connection' object has no attribute 'conn'
2023-01-13 22:10:20,913 ERROR   Error in recurse_quadtree
Traceback (most recent call last):
  File "C:\ufop\airbnb-data-collection\airbnb_listing.py", line 157, in save
    self.__insert()
  File "C:\ufop\airbnb-data-collection\airbnb_listing.py", line 328, in __insert
    cur.execute(sql, insert_args)
psycopg2.errors.NumericValueOutOfRange: integer out of range


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\ufop\airbnb-data-collection\airbnb_survey.py", line 506, in recurse_quadtree
    (zoomable, median_leaf) = self.search_node(
                              ^^^^^^^^^^^^^^^^^
  File "C:\ufop\airbnb-data-collection\airbnb_survey.py", line 781, in search_node
    if listing.save(self.config.FLAGS_INSERT_NO_REPLACE):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ufop\airbnb-data-collection\airbnb_listing.py", line 167, in save
    self.config.connection.conn.rollback()
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'psycopg2.extensions.connection' object has no attribute 'conn'
2023-01-13 22:10:20,918 ERROR   Error
Traceback (most recent call last):
  File "C:\ufop\airbnb-data-collection\airbnb_listing.py", line 157, in save
    self.__insert()
  File "C:\ufop\airbnb-data-collection\airbnb_listing.py", line 328, in __insert
    cur.execute(sql, insert_args)
psycopg2.errors.NumericValueOutOfRange: integer out of range


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\ufop\airbnb-data-collection\airbnb_survey.py", line 445, in search
    self.recurse_quadtree(quadtree_node, median_node, None, flag)
  File "C:\ufop\airbnb-data-collection\airbnb_survey.py", line 506, in recurse_quadtree
    (zoomable, median_leaf) = self.search_node(
                              ^^^^^^^^^^^^^^^^^
  File "C:\ufop\airbnb-data-collection\airbnb_survey.py", line 781, in search_node
    if listing.save(self.config.FLAGS_INSERT_NO_REPLACE):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ufop\airbnb-data-collection\airbnb_listing.py", line 167, in save
    self.config.connection.conn.rollback()
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'psycopg2.extensions.connection' object has no attribute 'conn'
2023-01-13 22:11:43,211 INFO    ======================================================================
2023-01-13 22:11:43,212 INFO    Survey 7, for Ouro Preto
2023-01-13 22:11:43,213 INFO    Searching by bounding box, max_zoom=24
2023-01-13 22:11:43,214 INFO    ----------------------------------------------------------------------
2023-01-13 22:11:43,214 INFO    Rectangle calculated: [-20.2519, -43.4372, -20.5229, -43.7846]
2023-01-13 22:11:43,215 INFO    Searching rectangle: zoom factor = 0, node = []
2023-01-13 22:11:43,365 WARNING HTTP status 403 from web site: IP address blocked. Waiting 1.0 minutes.
2023-01-13 22:12:45,276 ERROR   Exception in get_search_page_info_rectangle
Traceback (most recent call last):
  File "C:\ufop\airbnb-data-collection\airbnb_listing.py", line 157, in save
    self.__insert()
  File "C:\ufop\airbnb-data-collection\airbnb_listing.py", line 330, in __insert
    cur.execute(sql, insert_args)
psycopg2.errors.NumericValueOutOfRange: integer out of range


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\ufop\airbnb-data-collection\airbnb_survey.py", line 781, in search_node
    if listing.save(self.config.FLAGS_INSERT_NO_REPLACE):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ufop\airbnb-data-collection\airbnb_listing.py", line 167, in save
    self.config.connection.conn.rollback()
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'psycopg2.extensions.connection' object has no attribute 'conn'
2023-01-13 22:12:45,280 ERROR   Error in recurse_quadtree
Traceback (most recent call last):
  File "C:\ufop\airbnb-data-collection\airbnb_listing.py", line 157, in save
    self.__insert()
  File "C:\ufop\airbnb-data-collection\airbnb_listing.py", line 330, in __insert
    cur.execute(sql, insert_args)
psycopg2.errors.NumericValueOutOfRange: integer out of range


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\ufop\airbnb-data-collection\airbnb_survey.py", line 506, in recurse_quadtree
    (zoomable, median_leaf) = self.search_node(
                              ^^^^^^^^^^^^^^^^^
  File "C:\ufop\airbnb-data-collection\airbnb_survey.py", line 781, in search_node
    if listing.save(self.config.FLAGS_INSERT_NO_REPLACE):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ufop\airbnb-data-collection\airbnb_listing.py", line 167, in save
    self.config.connection.conn.rollback()
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'psycopg2.extensions.connection' object has no attribute 'conn'
2023-01-13 22:12:45,284 ERROR   Error
Traceback (most recent call last):
  File "C:\ufop\airbnb-data-collection\airbnb_listing.py", line 157, in save
    self.__insert()
  File "C:\ufop\airbnb-data-collection\airbnb_listing.py", line 330, in __insert
    cur.execute(sql, insert_args)
psycopg2.errors.NumericValueOutOfRange: integer out of range


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\ufop\airbnb-data-collection\airbnb_survey.py", line 445, in search
    self.recurse_quadtree(quadtree_node, median_node, None, flag)
  File "C:\ufop\airbnb-data-collection\airbnb_survey.py", line 506, in recurse_quadtree
    (zoomable, median_leaf) = self.search_node(
                              ^^^^^^^^^^^^^^^^^
  File "C:\ufop\airbnb-data-collection\airbnb_survey.py", line 781, in search_node
    if listing.save(self.config.FLAGS_INSERT_NO_REPLACE):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ufop\airbnb-data-collection\airbnb_listing.py", line 167, in save
    self.config.connection.conn.rollback()
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'psycopg2.extensions.connection' object has no attribute 'conn'
2023-01-13 22:13:05,110 INFO    ======================================================================
2023-01-13 22:13:05,111 INFO    Survey 7, for Ouro Preto
2023-01-13 22:13:05,111 INFO    Searching by bounding box, max_zoom=24
2023-01-13 22:13:05,112 INFO    ----------------------------------------------------------------------
2023-01-13 22:13:05,112 INFO    Rectangle calculated: [-20.2519, -43.4372, -20.5229, -43.7846]
2023-01-13 22:13:05,112 INFO    Searching rectangle: zoom factor = 0, node = []
2023-01-13 22:13:06,467 ERROR   Exception in get_search_page_info_rectangle
Traceback (most recent call last):
  File "C:\ufop\airbnb-data-collection\airbnb_listing.py", line 157, in save
    self.__insert()
  File "C:\ufop\airbnb-data-collection\airbnb_listing.py", line 330, in __insert
    cur.execute(sql, insert_args)
psycopg2.errors.NumericValueOutOfRange: integer out of range


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\ufop\airbnb-data-collection\airbnb_survey.py", line 781, in search_node
    if listing.save(self.config.FLAGS_INSERT_NO_REPLACE):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ufop\airbnb-data-collection\airbnb_listing.py", line 167, in save
    self.config.connection.conn.rollback()
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'psycopg2.extensions.connection' object has no attribute 'conn'
2023-01-13 22:13:06,475 ERROR   Error in recurse_quadtree
Traceback (most recent call last):
  File "C:\ufop\airbnb-data-collection\airbnb_listing.py", line 157, in save
    self.__insert()
  File "C:\ufop\airbnb-data-collection\airbnb_listing.py", line 330, in __insert
    cur.execute(sql, insert_args)
psycopg2.errors.NumericValueOutOfRange: integer out of range


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\ufop\airbnb-data-collection\airbnb_survey.py", line 506, in recurse_quadtree
    (zoomable, median_leaf) = self.search_node(
                              ^^^^^^^^^^^^^^^^^
  File "C:\ufop\airbnb-data-collection\airbnb_survey.py", line 781, in search_node
    if listing.save(self.config.FLAGS_INSERT_NO_REPLACE):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ufop\airbnb-data-collection\airbnb_listing.py", line 167, in save
    self.config.connection.conn.rollback()
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'psycopg2.extensions.connection' object has no attribute 'conn'
2023-01-13 22:13:06,480 ERROR   Error
Traceback (most recent call last):
  File "C:\ufop\airbnb-data-collection\airbnb_listing.py", line 157, in save
    self.__insert()
  File "C:\ufop\airbnb-data-collection\airbnb_listing.py", line 330, in __insert
    cur.execute(sql, insert_args)
psycopg2.errors.NumericValueOutOfRange: integer out of range


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\ufop\airbnb-data-collection\airbnb_survey.py", line 445, in search
    self.recurse_quadtree(quadtree_node, median_node, None, flag)
  File "C:\ufop\airbnb-data-collection\airbnb_survey.py", line 506, in recurse_quadtree
    (zoomable, median_leaf) = self.search_node(
                              ^^^^^^^^^^^^^^^^^
  File "C:\ufop\airbnb-data-collection\airbnb_survey.py", line 781, in search_node
    if listing.save(self.config.FLAGS_INSERT_NO_REPLACE):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ufop\airbnb-data-collection\airbnb_listing.py", line 167, in save
    self.config.connection.conn.rollback()
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'psycopg2.extensions.connection' object has no attribute 'conn'
2023-01-13 22:18:28,697 INFO    ======================================================================
2023-01-13 22:18:28,698 INFO    Survey 7, for Ouro Preto
2023-01-13 22:18:28,699 INFO    Searching by bounding box, max_zoom=24
2023-01-13 22:18:28,699 INFO    ----------------------------------------------------------------------
2023-01-13 22:18:28,700 INFO    Rectangle calculated: [-20.2519, -43.4372, -20.5229, -43.7846]
2023-01-13 22:18:28,701 INFO    Searching rectangle: zoom factor = 0, node = []
2023-01-13 22:18:29,777 ERROR   Exception saving room
2023-01-13 22:18:29,778 ERROR   Exception in get_search_page_info_rectangle
Traceback (most recent call last):
  File "C:\ufop\airbnb-data-collection\airbnb_survey.py", line 781, in search_node
    if listing.save(self.config.FLAGS_INSERT_NO_REPLACE):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ufop\airbnb-data-collection\airbnb_listing.py", line 157, in save
    self.__insert()
  File "C:\ufop\airbnb-data-collection\airbnb_listing.py", line 330, in __insert
    cur.execute(sql, insert_args)
TypeError: not all arguments converted during string formatting
2023-01-13 22:18:29,782 ERROR   TypeError in recurse_quadtree
Traceback (most recent call last):
  File "C:\ufop\airbnb-data-collection\airbnb_survey.py", line 506, in recurse_quadtree
    (zoomable, median_leaf) = self.search_node(
                              ^^^^^^^^^^^^^^^^^
  File "C:\ufop\airbnb-data-collection\airbnb_survey.py", line 781, in search_node
    if listing.save(self.config.FLAGS_INSERT_NO_REPLACE):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ufop\airbnb-data-collection\airbnb_listing.py", line 157, in save
    self.__insert()
  File "C:\ufop\airbnb-data-collection\airbnb_listing.py", line 330, in __insert
    cur.execute(sql, insert_args)
TypeError: not all arguments converted during string formatting
2023-01-13 22:18:29,785 ERROR   ('not all arguments converted during string formatting',)
2023-01-13 22:18:29,785 ERROR   Error
Traceback (most recent call last):
  File "C:\ufop\airbnb-data-collection\airbnb_survey.py", line 445, in search
    self.recurse_quadtree(quadtree_node, median_node, None, flag)
  File "C:\ufop\airbnb-data-collection\airbnb_survey.py", line 506, in recurse_quadtree
    (zoomable, median_leaf) = self.search_node(
                              ^^^^^^^^^^^^^^^^^
  File "C:\ufop\airbnb-data-collection\airbnb_survey.py", line 781, in search_node
    if listing.save(self.config.FLAGS_INSERT_NO_REPLACE):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ufop\airbnb-data-collection\airbnb_listing.py", line 157, in save
    self.__insert()
  File "C:\ufop\airbnb-data-collection\airbnb_listing.py", line 330, in __insert
    cur.execute(sql, insert_args)
TypeError: not all arguments converted during string formatting
2023-01-13 22:19:47,526 INFO    ======================================================================
2023-01-13 22:19:47,527 INFO    Survey 7, for Ouro Preto
2023-01-13 22:19:47,528 INFO    Searching by bounding box, max_zoom=24
2023-01-13 22:19:47,528 INFO    ----------------------------------------------------------------------
2023-01-13 22:19:47,529 INFO    Rectangle calculated: [-20.2519, -43.4372, -20.5229, -43.7846]
2023-01-13 22:19:47,529 INFO    Searching rectangle: zoom factor = 0, node = []
2023-01-13 22:19:48,300 ERROR   Exception in get_search_page_info_rectangle
Traceback (most recent call last):
  File "C:\ufop\airbnb-data-collection\airbnb_listing.py", line 157, in save
    self.__insert()
  File "C:\ufop\airbnb-data-collection\airbnb_listing.py", line 330, in __insert
    cur.execute(sql, insert_args)
psycopg2.errors.NumericValueOutOfRange: integer out of range


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\ufop\airbnb-data-collection\airbnb_survey.py", line 781, in search_node
    if listing.save(self.config.FLAGS_INSERT_NO_REPLACE):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ufop\airbnb-data-collection\airbnb_listing.py", line 167, in save
    self.config.connection.conn.rollback()
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'psycopg2.extensions.connection' object has no attribute 'conn'
2023-01-13 22:19:48,304 ERROR   Error in recurse_quadtree
Traceback (most recent call last):
  File "C:\ufop\airbnb-data-collection\airbnb_listing.py", line 157, in save
    self.__insert()
  File "C:\ufop\airbnb-data-collection\airbnb_listing.py", line 330, in __insert
    cur.execute(sql, insert_args)
psycopg2.errors.NumericValueOutOfRange: integer out of range


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\ufop\airbnb-data-collection\airbnb_survey.py", line 506, in recurse_quadtree
    (zoomable, median_leaf) = self.search_node(
                              ^^^^^^^^^^^^^^^^^
  File "C:\ufop\airbnb-data-collection\airbnb_survey.py", line 781, in search_node
    if listing.save(self.config.FLAGS_INSERT_NO_REPLACE):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ufop\airbnb-data-collection\airbnb_listing.py", line 167, in save
    self.config.connection.conn.rollback()
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'psycopg2.extensions.connection' object has no attribute 'conn'
2023-01-13 22:19:48,307 ERROR   Error
Traceback (most recent call last):
  File "C:\ufop\airbnb-data-collection\airbnb_listing.py", line 157, in save
    self.__insert()
  File "C:\ufop\airbnb-data-collection\airbnb_listing.py", line 330, in __insert
    cur.execute(sql, insert_args)
psycopg2.errors.NumericValueOutOfRange: integer out of range


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\ufop\airbnb-data-collection\airbnb_survey.py", line 445, in search
    self.recurse_quadtree(quadtree_node, median_node, None, flag)
  File "C:\ufop\airbnb-data-collection\airbnb_survey.py", line 506, in recurse_quadtree
    (zoomable, median_leaf) = self.search_node(
                              ^^^^^^^^^^^^^^^^^
  File "C:\ufop\airbnb-data-collection\airbnb_survey.py", line 781, in search_node
    if listing.save(self.config.FLAGS_INSERT_NO_REPLACE):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ufop\airbnb-data-collection\airbnb_listing.py", line 167, in save
    self.config.connection.conn.rollback()
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'psycopg2.extensions.connection' object has no attribute 'conn'
2023-01-13 22:20:16,003 INFO    ======================================================================
2023-01-13 22:20:16,004 INFO    Survey 7, for Ouro Preto
2023-01-13 22:20:16,004 INFO    Searching by bounding box, max_zoom=24
2023-01-13 22:20:16,005 INFO    ----------------------------------------------------------------------
2023-01-13 22:20:16,005 INFO    Rectangle calculated: [-20.2519, -43.4372, -20.5229, -43.7846]
2023-01-13 22:20:16,005 INFO    Searching rectangle: zoom factor = 0, node = []
2023-01-13 22:20:16,876 ERROR   Exception in get_search_page_info_rectangle
Traceback (most recent call last):
  File "C:\ufop\airbnb-data-collection\airbnb_listing.py", line 157, in save
    self.__insert()
  File "C:\ufop\airbnb-data-collection\airbnb_listing.py", line 330, in __insert
    cur.execute(sql, insert_args)
psycopg2.errors.NumericValueOutOfRange: integer out of range


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\ufop\airbnb-data-collection\airbnb_survey.py", line 781, in search_node
    if listing.save(self.config.FLAGS_INSERT_NO_REPLACE):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ufop\airbnb-data-collection\airbnb_listing.py", line 167, in save
    self.config.connection.conn.rollback()
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'psycopg2.extensions.connection' object has no attribute 'conn'
2023-01-13 22:20:16,880 ERROR   Error in recurse_quadtree
Traceback (most recent call last):
  File "C:\ufop\airbnb-data-collection\airbnb_listing.py", line 157, in save
    self.__insert()
  File "C:\ufop\airbnb-data-collection\airbnb_listing.py", line 330, in __insert
    cur.execute(sql, insert_args)
psycopg2.errors.NumericValueOutOfRange: integer out of range


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\ufop\airbnb-data-collection\airbnb_survey.py", line 506, in recurse_quadtree
    (zoomable, median_leaf) = self.search_node(
                              ^^^^^^^^^^^^^^^^^
  File "C:\ufop\airbnb-data-collection\airbnb_survey.py", line 781, in search_node
    if listing.save(self.config.FLAGS_INSERT_NO_REPLACE):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ufop\airbnb-data-collection\airbnb_listing.py", line 167, in save
    self.config.connection.conn.rollback()
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'psycopg2.extensions.connection' object has no attribute 'conn'
2023-01-13 22:20:16,885 ERROR   Error
Traceback (most recent call last):
  File "C:\ufop\airbnb-data-collection\airbnb_listing.py", line 157, in save
    self.__insert()
  File "C:\ufop\airbnb-data-collection\airbnb_listing.py", line 330, in __insert
    cur.execute(sql, insert_args)
psycopg2.errors.NumericValueOutOfRange: integer out of range


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\ufop\airbnb-data-collection\airbnb_survey.py", line 445, in search
    self.recurse_quadtree(quadtree_node, median_node, None, flag)
  File "C:\ufop\airbnb-data-collection\airbnb_survey.py", line 506, in recurse_quadtree
    (zoomable, median_leaf) = self.search_node(
                              ^^^^^^^^^^^^^^^^^
  File "C:\ufop\airbnb-data-collection\airbnb_survey.py", line 781, in search_node
    if listing.save(self.config.FLAGS_INSERT_NO_REPLACE):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ufop\airbnb-data-collection\airbnb_listing.py", line 167, in save
    self.config.connection.conn.rollback()
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'psycopg2.extensions.connection' object has no attribute 'conn'
2023-01-13 22:21:34,888 INFO    ======================================================================
2023-01-13 22:21:34,888 INFO    Survey 7, for Ouro Preto
2023-01-13 22:21:34,889 INFO    Searching by bounding box, max_zoom=24
2023-01-13 22:21:34,889 INFO    ----------------------------------------------------------------------
2023-01-13 22:21:34,890 INFO    Rectangle calculated: [-20.2519, -43.4372, -20.5229, -43.7846]
2023-01-13 22:21:34,890 INFO    Searching rectangle: zoom factor = 0, node = []
2023-01-13 22:21:36,134 ERROR   Exception in get_search_page_info_rectangle
Traceback (most recent call last):
  File "C:\ufop\airbnb-data-collection\airbnb_listing.py", line 157, in save
    self.__insert()
  File "C:\ufop\airbnb-data-collection\airbnb_listing.py", line 330, in __insert
    cur.execute(sql, insert_args)
psycopg2.errors.NumericValueOutOfRange: integer out of range


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\ufop\airbnb-data-collection\airbnb_survey.py", line 781, in search_node
    if listing.save(self.config.FLAGS_INSERT_NO_REPLACE):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ufop\airbnb-data-collection\airbnb_listing.py", line 167, in save
    self.config.connection.conn.rollback()
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'psycopg2.extensions.connection' object has no attribute 'conn'
2023-01-13 22:21:36,142 ERROR   Error in recurse_quadtree
Traceback (most recent call last):
  File "C:\ufop\airbnb-data-collection\airbnb_listing.py", line 157, in save
    self.__insert()
  File "C:\ufop\airbnb-data-collection\airbnb_listing.py", line 330, in __insert
    cur.execute(sql, insert_args)
psycopg2.errors.NumericValueOutOfRange: integer out of range


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\ufop\airbnb-data-collection\airbnb_survey.py", line 506, in recurse_quadtree
    (zoomable, median_leaf) = self.search_node(
                              ^^^^^^^^^^^^^^^^^
  File "C:\ufop\airbnb-data-collection\airbnb_survey.py", line 781, in search_node
    if listing.save(self.config.FLAGS_INSERT_NO_REPLACE):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ufop\airbnb-data-collection\airbnb_listing.py", line 167, in save
    self.config.connection.conn.rollback()
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'psycopg2.extensions.connection' object has no attribute 'conn'
2023-01-13 22:21:36,148 ERROR   Error
Traceback (most recent call last):
  File "C:\ufop\airbnb-data-collection\airbnb_listing.py", line 157, in save
    self.__insert()
  File "C:\ufop\airbnb-data-collection\airbnb_listing.py", line 330, in __insert
    cur.execute(sql, insert_args)
psycopg2.errors.NumericValueOutOfRange: integer out of range


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\ufop\airbnb-data-collection\airbnb_survey.py", line 445, in search
    self.recurse_quadtree(quadtree_node, median_node, None, flag)
  File "C:\ufop\airbnb-data-collection\airbnb_survey.py", line 506, in recurse_quadtree
    (zoomable, median_leaf) = self.search_node(
                              ^^^^^^^^^^^^^^^^^
  File "C:\ufop\airbnb-data-collection\airbnb_survey.py", line 781, in search_node
    if listing.save(self.config.FLAGS_INSERT_NO_REPLACE):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ufop\airbnb-data-collection\airbnb_listing.py", line 167, in save
    self.config.connection.conn.rollback()
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'psycopg2.extensions.connection' object has no attribute 'conn'
2023-01-13 22:22:53,954 INFO    ======================================================================
2023-01-13 22:22:53,955 INFO    Survey 7, for Ouro Preto
2023-01-13 22:22:53,956 INFO    Searching by bounding box, max_zoom=24
2023-01-13 22:22:53,956 INFO    ----------------------------------------------------------------------
2023-01-13 22:22:53,956 INFO    Rectangle calculated: [-20.2519, -43.4372, -20.5229, -43.7846]
2023-01-13 22:22:53,957 INFO    Searching rectangle: zoom factor = 0, node = []
2023-01-13 22:22:55,286 ERROR   Exception in get_search_page_info_rectangle
Traceback (most recent call last):
  File "C:\ufop\airbnb-data-collection\airbnb_listing.py", line 157, in save
    self.__insert()
  File "C:\ufop\airbnb-data-collection\airbnb_listing.py", line 330, in __insert
    cur.execute(sql, insert_args)
psycopg2.errors.NumericValueOutOfRange: integer out of range


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\ufop\airbnb-data-collection\airbnb_survey.py", line 781, in search_node
    if listing.save(self.config.FLAGS_INSERT_NO_REPLACE):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ufop\airbnb-data-collection\airbnb_listing.py", line 167, in save
    self.config.connection.conn.rollback()
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'psycopg2.extensions.connection' object has no attribute 'conn'
2023-01-13 22:22:55,290 ERROR   Error in recurse_quadtree
Traceback (most recent call last):
  File "C:\ufop\airbnb-data-collection\airbnb_listing.py", line 157, in save
    self.__insert()
  File "C:\ufop\airbnb-data-collection\airbnb_listing.py", line 330, in __insert
    cur.execute(sql, insert_args)
psycopg2.errors.NumericValueOutOfRange: integer out of range


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\ufop\airbnb-data-collection\airbnb_survey.py", line 506, in recurse_quadtree
    (zoomable, median_leaf) = self.search_node(
                              ^^^^^^^^^^^^^^^^^
  File "C:\ufop\airbnb-data-collection\airbnb_survey.py", line 781, in search_node
    if listing.save(self.config.FLAGS_INSERT_NO_REPLACE):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ufop\airbnb-data-collection\airbnb_listing.py", line 167, in save
    self.config.connection.conn.rollback()
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'psycopg2.extensions.connection' object has no attribute 'conn'
2023-01-13 22:22:55,294 ERROR   Error
Traceback (most recent call last):
  File "C:\ufop\airbnb-data-collection\airbnb_listing.py", line 157, in save
    self.__insert()
  File "C:\ufop\airbnb-data-collection\airbnb_listing.py", line 330, in __insert
    cur.execute(sql, insert_args)
psycopg2.errors.NumericValueOutOfRange: integer out of range


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\ufop\airbnb-data-collection\airbnb_survey.py", line 445, in search
    self.recurse_quadtree(quadtree_node, median_node, None, flag)
  File "C:\ufop\airbnb-data-collection\airbnb_survey.py", line 506, in recurse_quadtree
    (zoomable, median_leaf) = self.search_node(
                              ^^^^^^^^^^^^^^^^^
  File "C:\ufop\airbnb-data-collection\airbnb_survey.py", line 781, in search_node
    if listing.save(self.config.FLAGS_INSERT_NO_REPLACE):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ufop\airbnb-data-collection\airbnb_listing.py", line 167, in save
    self.config.connection.conn.rollback()
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'psycopg2.extensions.connection' object has no attribute 'conn'
2023-01-13 22:24:36,686 INFO    ======================================================================
2023-01-13 22:24:36,687 INFO    Survey 7, for Ouro Preto
2023-01-13 22:24:36,688 INFO    Searching by bounding box, max_zoom=24
2023-01-13 22:24:36,688 INFO    ----------------------------------------------------------------------
2023-01-13 22:24:36,689 INFO    Rectangle calculated: [-20.2519, -43.4372, -20.5229, -43.7846]
2023-01-13 22:24:36,690 INFO    Searching rectangle: zoom factor = 0, node = []
2023-01-13 22:24:37,689 ERROR   Exception in get_search_page_info_rectangle
Traceback (most recent call last):
  File "C:\ufop\airbnb-data-collection\airbnb_listing.py", line 157, in save
    self.__insert()
  File "C:\ufop\airbnb-data-collection\airbnb_listing.py", line 330, in __insert
    cur.execute(sql, insert_args)
psycopg2.errors.NumericValueOutOfRange: integer out of range


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\ufop\airbnb-data-collection\airbnb_survey.py", line 781, in search_node
    if listing.save(self.config.FLAGS_INSERT_NO_REPLACE):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ufop\airbnb-data-collection\airbnb_listing.py", line 167, in save
    self.config.connection.conn.rollback()
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'psycopg2.extensions.connection' object has no attribute 'conn'
2023-01-13 22:24:37,693 ERROR   Error in recurse_quadtree
Traceback (most recent call last):
  File "C:\ufop\airbnb-data-collection\airbnb_listing.py", line 157, in save
    self.__insert()
  File "C:\ufop\airbnb-data-collection\airbnb_listing.py", line 330, in __insert
    cur.execute(sql, insert_args)
psycopg2.errors.NumericValueOutOfRange: integer out of range


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\ufop\airbnb-data-collection\airbnb_survey.py", line 506, in recurse_quadtree
    (zoomable, median_leaf) = self.search_node(
                              ^^^^^^^^^^^^^^^^^
  File "C:\ufop\airbnb-data-collection\airbnb_survey.py", line 781, in search_node
    if listing.save(self.config.FLAGS_INSERT_NO_REPLACE):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ufop\airbnb-data-collection\airbnb_listing.py", line 167, in save
    self.config.connection.conn.rollback()
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'psycopg2.extensions.connection' object has no attribute 'conn'
2023-01-13 22:24:37,696 ERROR   Error
Traceback (most recent call last):
  File "C:\ufop\airbnb-data-collection\airbnb_listing.py", line 157, in save
    self.__insert()
  File "C:\ufop\airbnb-data-collection\airbnb_listing.py", line 330, in __insert
    cur.execute(sql, insert_args)
psycopg2.errors.NumericValueOutOfRange: integer out of range


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\ufop\airbnb-data-collection\airbnb_survey.py", line 445, in search
    self.recurse_quadtree(quadtree_node, median_node, None, flag)
  File "C:\ufop\airbnb-data-collection\airbnb_survey.py", line 506, in recurse_quadtree
    (zoomable, median_leaf) = self.search_node(
                              ^^^^^^^^^^^^^^^^^
  File "C:\ufop\airbnb-data-collection\airbnb_survey.py", line 781, in search_node
    if listing.save(self.config.FLAGS_INSERT_NO_REPLACE):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ufop\airbnb-data-collection\airbnb_listing.py", line 167, in save
    self.config.connection.conn.rollback()
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'psycopg2.extensions.connection' object has no attribute 'conn'
2023-01-13 22:27:17,328 INFO    ======================================================================
2023-01-13 22:27:17,329 INFO    Survey 7, for Ouro Preto
2023-01-13 22:27:17,329 INFO    Searching by bounding box, max_zoom=24
2023-01-13 22:27:17,330 INFO    ----------------------------------------------------------------------
2023-01-13 22:27:17,330 INFO    Rectangle calculated: [-20.2519, -43.4372, -20.5229, -43.7846]
2023-01-13 22:27:17,330 INFO    Searching rectangle: zoom factor = 0, node = []
2023-01-13 22:27:18,410 ERROR   Exception in get_search_page_info_rectangle
Traceback (most recent call last):
  File "C:\ufop\airbnb-data-collection\airbnb_listing.py", line 157, in save
    self.__insert()
  File "C:\ufop\airbnb-data-collection\airbnb_listing.py", line 330, in __insert
    cur.execute(sql, insert_args)
psycopg2.errors.NumericValueOutOfRange: integer out of range


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\ufop\airbnb-data-collection\airbnb_survey.py", line 782, in search_node
    if listing.save(self.config.FLAGS_INSERT_NO_REPLACE):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ufop\airbnb-data-collection\airbnb_listing.py", line 167, in save
    self.config.connection.conn.rollback()
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'psycopg2.extensions.connection' object has no attribute 'conn'
2023-01-13 22:27:18,419 ERROR   Error in recurse_quadtree
Traceback (most recent call last):
  File "C:\ufop\airbnb-data-collection\airbnb_listing.py", line 157, in save
    self.__insert()
  File "C:\ufop\airbnb-data-collection\airbnb_listing.py", line 330, in __insert
    cur.execute(sql, insert_args)
psycopg2.errors.NumericValueOutOfRange: integer out of range


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\ufop\airbnb-data-collection\airbnb_survey.py", line 506, in recurse_quadtree
    (zoomable, median_leaf) = self.search_node(
                              ^^^^^^^^^^^^^^^^^
  File "C:\ufop\airbnb-data-collection\airbnb_survey.py", line 782, in search_node
    if listing.save(self.config.FLAGS_INSERT_NO_REPLACE):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ufop\airbnb-data-collection\airbnb_listing.py", line 167, in save
    self.config.connection.conn.rollback()
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'psycopg2.extensions.connection' object has no attribute 'conn'
2023-01-13 22:27:18,426 ERROR   Error
Traceback (most recent call last):
  File "C:\ufop\airbnb-data-collection\airbnb_listing.py", line 157, in save
    self.__insert()
  File "C:\ufop\airbnb-data-collection\airbnb_listing.py", line 330, in __insert
    cur.execute(sql, insert_args)
psycopg2.errors.NumericValueOutOfRange: integer out of range


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\ufop\airbnb-data-collection\airbnb_survey.py", line 445, in search
    self.recurse_quadtree(quadtree_node, median_node, None, flag)
  File "C:\ufop\airbnb-data-collection\airbnb_survey.py", line 506, in recurse_quadtree
    (zoomable, median_leaf) = self.search_node(
                              ^^^^^^^^^^^^^^^^^
  File "C:\ufop\airbnb-data-collection\airbnb_survey.py", line 782, in search_node
    if listing.save(self.config.FLAGS_INSERT_NO_REPLACE):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ufop\airbnb-data-collection\airbnb_listing.py", line 167, in save
    self.config.connection.conn.rollback()
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'psycopg2.extensions.connection' object has no attribute 'conn'
2023-01-13 22:32:14,531 INFO    ======================================================================
2023-01-13 22:32:14,531 INFO    Survey 7, for Ouro Preto
2023-01-13 22:32:14,532 INFO    Searching by bounding box, max_zoom=24
2023-01-13 22:32:14,532 INFO    ----------------------------------------------------------------------
2023-01-13 22:32:14,533 INFO    Rectangle calculated: [-20.2519, -43.4372, -20.5229, -43.7846]
2023-01-13 22:32:14,533 INFO    Searching rectangle: zoom factor = 0, node = []
2023-01-13 22:32:14,825 WARNING HTTP status 403 from web site: IP address blocked. Waiting 1.0 minutes.
2023-01-13 22:33:16,401 WARNING HTTP status 403 from web site: IP address blocked. Waiting 1.0 minutes.
2023-01-13 22:34:19,144 ERROR   Exception in get_search_page_info_rectangle
Traceback (most recent call last):
  File "C:\ufop\airbnb-data-collection\airbnb_listing.py", line 157, in save
    self.__insert()
  File "C:\ufop\airbnb-data-collection\airbnb_listing.py", line 330, in __insert
    cur.execute(sql, insert_args)
psycopg2.errors.NumericValueOutOfRange: integer out of range


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\ufop\airbnb-data-collection\airbnb_survey.py", line 784, in search_node
    if listing.save(self.config.FLAGS_INSERT_NO_REPLACE):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ufop\airbnb-data-collection\airbnb_listing.py", line 167, in save
    self.config.connection.conn.rollback()
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'psycopg2.extensions.connection' object has no attribute 'conn'
2023-01-13 22:34:19,149 ERROR   Error in recurse_quadtree
Traceback (most recent call last):
  File "C:\ufop\airbnb-data-collection\airbnb_listing.py", line 157, in save
    self.__insert()
  File "C:\ufop\airbnb-data-collection\airbnb_listing.py", line 330, in __insert
    cur.execute(sql, insert_args)
psycopg2.errors.NumericValueOutOfRange: integer out of range


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\ufop\airbnb-data-collection\airbnb_survey.py", line 506, in recurse_quadtree
    (zoomable, median_leaf) = self.search_node(
                              ^^^^^^^^^^^^^^^^^
  File "C:\ufop\airbnb-data-collection\airbnb_survey.py", line 784, in search_node
    if listing.save(self.config.FLAGS_INSERT_NO_REPLACE):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ufop\airbnb-data-collection\airbnb_listing.py", line 167, in save
    self.config.connection.conn.rollback()
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'psycopg2.extensions.connection' object has no attribute 'conn'
2023-01-13 22:34:19,155 ERROR   Error
Traceback (most recent call last):
  File "C:\ufop\airbnb-data-collection\airbnb_listing.py", line 157, in save
    self.__insert()
  File "C:\ufop\airbnb-data-collection\airbnb_listing.py", line 330, in __insert
    cur.execute(sql, insert_args)
psycopg2.errors.NumericValueOutOfRange: integer out of range


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\ufop\airbnb-data-collection\airbnb_survey.py", line 445, in search
    self.recurse_quadtree(quadtree_node, median_node, None, flag)
  File "C:\ufop\airbnb-data-collection\airbnb_survey.py", line 506, in recurse_quadtree
    (zoomable, median_leaf) = self.search_node(
                              ^^^^^^^^^^^^^^^^^
  File "C:\ufop\airbnb-data-collection\airbnb_survey.py", line 784, in search_node
    if listing.save(self.config.FLAGS_INSERT_NO_REPLACE):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ufop\airbnb-data-collection\airbnb_listing.py", line 167, in save
    self.config.connection.conn.rollback()
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'psycopg2.extensions.connection' object has no attribute 'conn'
2023-01-13 22:37:54,331 INFO    ======================================================================
2023-01-13 22:37:54,332 INFO    Survey 7, for Ouro Preto
2023-01-13 22:37:54,352 INFO    Searching by bounding box, max_zoom=24
2023-01-13 22:37:54,353 INFO    ----------------------------------------------------------------------
2023-01-13 22:37:54,354 INFO    Rectangle calculated: [-20.2519, -43.4372, -20.5229, -43.7846]
2023-01-13 22:37:54,354 INFO    Searching rectangle: zoom factor = 0, node = []
2023-01-13 22:37:54,741 WARNING HTTP status 403 from web site: IP address blocked. Waiting 1.0 minutes.
2023-01-13 22:38:57,231 ERROR   Exception saving room
2023-01-13 22:38:57,234 ERROR   Exception in get_search_page_info_rectangle
Traceback (most recent call last):
  File "C:\ufop\airbnb-data-collection\airbnb_survey.py", line 784, in search_node
    if listing.save(self.config.FLAGS_INSERT_NO_REPLACE):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ufop\airbnb-data-collection\airbnb_listing.py", line 157, in save
    self.__insert()
  File "C:\ufop\airbnb-data-collection\airbnb_listing.py", line 330, in __insert
    cur.execute(sql, insert_args)
TypeError: not all arguments converted during string formatting
2023-01-13 22:38:57,238 ERROR   TypeError in recurse_quadtree
Traceback (most recent call last):
  File "C:\ufop\airbnb-data-collection\airbnb_survey.py", line 506, in recurse_quadtree
    (zoomable, median_leaf) = self.search_node(
                              ^^^^^^^^^^^^^^^^^
  File "C:\ufop\airbnb-data-collection\airbnb_survey.py", line 784, in search_node
    if listing.save(self.config.FLAGS_INSERT_NO_REPLACE):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ufop\airbnb-data-collection\airbnb_listing.py", line 157, in save
    self.__insert()
  File "C:\ufop\airbnb-data-collection\airbnb_listing.py", line 330, in __insert
    cur.execute(sql, insert_args)
TypeError: not all arguments converted during string formatting
2023-01-13 22:38:57,240 ERROR   ('not all arguments converted during string formatting',)
2023-01-13 22:38:57,240 ERROR   Error
Traceback (most recent call last):
  File "C:\ufop\airbnb-data-collection\airbnb_survey.py", line 445, in search
    self.recurse_quadtree(quadtree_node, median_node, None, flag)
  File "C:\ufop\airbnb-data-collection\airbnb_survey.py", line 506, in recurse_quadtree
    (zoomable, median_leaf) = self.search_node(
                              ^^^^^^^^^^^^^^^^^
  File "C:\ufop\airbnb-data-collection\airbnb_survey.py", line 784, in search_node
    if listing.save(self.config.FLAGS_INSERT_NO_REPLACE):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ufop\airbnb-data-collection\airbnb_listing.py", line 157, in save
    self.__insert()
  File "C:\ufop\airbnb-data-collection\airbnb_listing.py", line 330, in __insert
    cur.execute(sql, insert_args)
TypeError: not all arguments converted during string formatting
2023-01-13 22:44:16,789 INFO    ======================================================================
2023-01-13 22:44:16,790 INFO    Survey 7, for Ouro Preto
2023-01-13 22:44:16,791 INFO    Searching by bounding box, max_zoom=24
2023-01-13 22:44:16,791 INFO    ----------------------------------------------------------------------
2023-01-13 22:44:16,791 INFO    Rectangle calculated: [-20.2519, -43.4372, -20.5229, -43.7846]
2023-01-13 22:44:16,792 INFO    Searching rectangle: zoom factor = 0, node = []
2023-01-13 22:44:17,121 WARNING HTTP status 403 from web site: IP address blocked. Waiting 1.0 minutes.
2023-01-13 22:45:19,211 ERROR   Exception saving room
2023-01-13 22:45:19,211 ERROR   Exception in get_search_page_info_rectangle
Traceback (most recent call last):
  File "C:\ufop\airbnb-data-collection\airbnb_survey.py", line 784, in search_node
    if listing.save(self.config.FLAGS_INSERT_NO_REPLACE):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ufop\airbnb-data-collection\airbnb_listing.py", line 157, in save
    self.__insert()
  File "C:\ufop\airbnb-data-collection\airbnb_listing.py", line 328, in __insert
    cur.execute(sql, insert_args)
TypeError: not all arguments converted during string formatting
2023-01-13 22:45:19,220 ERROR   TypeError in recurse_quadtree
Traceback (most recent call last):
  File "C:\ufop\airbnb-data-collection\airbnb_survey.py", line 506, in recurse_quadtree
    (zoomable, median_leaf) = self.search_node(
                              ^^^^^^^^^^^^^^^^^
  File "C:\ufop\airbnb-data-collection\airbnb_survey.py", line 784, in search_node
    if listing.save(self.config.FLAGS_INSERT_NO_REPLACE):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ufop\airbnb-data-collection\airbnb_listing.py", line 157, in save
    self.__insert()
  File "C:\ufop\airbnb-data-collection\airbnb_listing.py", line 328, in __insert
    cur.execute(sql, insert_args)
TypeError: not all arguments converted during string formatting
2023-01-13 22:45:19,225 ERROR   ('not all arguments converted during string formatting',)
2023-01-13 22:45:19,226 ERROR   Error
Traceback (most recent call last):
  File "C:\ufop\airbnb-data-collection\airbnb_survey.py", line 445, in search
    self.recurse_quadtree(quadtree_node, median_node, None, flag)
  File "C:\ufop\airbnb-data-collection\airbnb_survey.py", line 506, in recurse_quadtree
    (zoomable, median_leaf) = self.search_node(
                              ^^^^^^^^^^^^^^^^^
  File "C:\ufop\airbnb-data-collection\airbnb_survey.py", line 784, in search_node
    if listing.save(self.config.FLAGS_INSERT_NO_REPLACE):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ufop\airbnb-data-collection\airbnb_listing.py", line 157, in save
    self.__insert()
  File "C:\ufop\airbnb-data-collection\airbnb_listing.py", line 328, in __insert
    cur.execute(sql, insert_args)
TypeError: not all arguments converted during string formatting
2023-01-13 22:46:28,853 INFO    ======================================================================
2023-01-13 22:46:28,854 INFO    Survey 7, for Ouro Preto
2023-01-13 22:46:28,855 INFO    Searching by bounding box, max_zoom=24
2023-01-13 22:46:28,855 INFO    ----------------------------------------------------------------------
2023-01-13 22:46:28,856 INFO    Rectangle calculated: [-20.2519, -43.4372, -20.5229, -43.7846]
2023-01-13 22:46:28,856 INFO    Searching rectangle: zoom factor = 0, node = []
2023-01-13 22:46:29,928 ERROR   Exception saving room
2023-01-13 22:46:29,928 ERROR   Exception in get_search_page_info_rectangle
Traceback (most recent call last):
  File "C:\ufop\airbnb-data-collection\airbnb_survey.py", line 784, in search_node
    if listing.save(self.config.FLAGS_INSERT_NO_REPLACE):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ufop\airbnb-data-collection\airbnb_listing.py", line 157, in save
    self.__insert()
  File "C:\ufop\airbnb-data-collection\airbnb_listing.py", line 328, in __insert
    cur.execute(sql, insert_args)
IndexError: tuple index out of range
2023-01-13 22:46:29,931 ERROR   Error in recurse_quadtree
Traceback (most recent call last):
  File "C:\ufop\airbnb-data-collection\airbnb_survey.py", line 506, in recurse_quadtree
    (zoomable, median_leaf) = self.search_node(
                              ^^^^^^^^^^^^^^^^^
  File "C:\ufop\airbnb-data-collection\airbnb_survey.py", line 784, in search_node
    if listing.save(self.config.FLAGS_INSERT_NO_REPLACE):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ufop\airbnb-data-collection\airbnb_listing.py", line 157, in save
    self.__insert()
  File "C:\ufop\airbnb-data-collection\airbnb_listing.py", line 328, in __insert
    cur.execute(sql, insert_args)
IndexError: tuple index out of range
2023-01-13 22:46:29,938 ERROR   Error
Traceback (most recent call last):
  File "C:\ufop\airbnb-data-collection\airbnb_survey.py", line 445, in search
    self.recurse_quadtree(quadtree_node, median_node, None, flag)
  File "C:\ufop\airbnb-data-collection\airbnb_survey.py", line 506, in recurse_quadtree
    (zoomable, median_leaf) = self.search_node(
                              ^^^^^^^^^^^^^^^^^
  File "C:\ufop\airbnb-data-collection\airbnb_survey.py", line 784, in search_node
    if listing.save(self.config.FLAGS_INSERT_NO_REPLACE):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ufop\airbnb-data-collection\airbnb_listing.py", line 157, in save
    self.__insert()
  File "C:\ufop\airbnb-data-collection\airbnb_listing.py", line 328, in __insert
    cur.execute(sql, insert_args)
IndexError: tuple index out of range
2023-01-13 22:48:59,597 INFO    ======================================================================
2023-01-13 22:48:59,600 INFO    Survey 7, for Ouro Preto
2023-01-13 22:48:59,603 INFO    Searching by bounding box, max_zoom=24
2023-01-13 22:48:59,604 INFO    ----------------------------------------------------------------------
2023-01-13 22:48:59,605 INFO    Rectangle calculated: [-20.2519, -43.4372, -20.5229, -43.7846]
2023-01-13 22:48:59,606 INFO    Searching rectangle: zoom factor = 0, node = []
2023-01-13 22:49:01,247 ERROR   Exception in get_search_page_info_rectangle
Traceback (most recent call last):
  File "C:\ufop\airbnb-data-collection\airbnb_listing.py", line 157, in save
    self.__insert()
  File "C:\ufop\airbnb-data-collection\airbnb_listing.py", line 327, in __insert
    cur.execute(sql, insert_args)
psycopg2.errors.NumericValueOutOfRange: integer out of range


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\ufop\airbnb-data-collection\airbnb_survey.py", line 784, in search_node
    if listing.save(self.config.FLAGS_INSERT_NO_REPLACE):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ufop\airbnb-data-collection\airbnb_listing.py", line 167, in save
    self.config.connection.conn.rollback()
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'psycopg2.extensions.connection' object has no attribute 'conn'
2023-01-13 22:49:01,261 ERROR   Error in recurse_quadtree
Traceback (most recent call last):
  File "C:\ufop\airbnb-data-collection\airbnb_listing.py", line 157, in save
    self.__insert()
  File "C:\ufop\airbnb-data-collection\airbnb_listing.py", line 327, in __insert
    cur.execute(sql, insert_args)
psycopg2.errors.NumericValueOutOfRange: integer out of range


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\ufop\airbnb-data-collection\airbnb_survey.py", line 506, in recurse_quadtree
    (zoomable, median_leaf) = self.search_node(
                              ^^^^^^^^^^^^^^^^^
  File "C:\ufop\airbnb-data-collection\airbnb_survey.py", line 784, in search_node
    if listing.save(self.config.FLAGS_INSERT_NO_REPLACE):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ufop\airbnb-data-collection\airbnb_listing.py", line 167, in save
    self.config.connection.conn.rollback()
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'psycopg2.extensions.connection' object has no attribute 'conn'
2023-01-13 22:49:01,273 ERROR   Error
Traceback (most recent call last):
  File "C:\ufop\airbnb-data-collection\airbnb_listing.py", line 157, in save
    self.__insert()
  File "C:\ufop\airbnb-data-collection\airbnb_listing.py", line 327, in __insert
    cur.execute(sql, insert_args)
psycopg2.errors.NumericValueOutOfRange: integer out of range


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\ufop\airbnb-data-collection\airbnb_survey.py", line 445, in search
    self.recurse_quadtree(quadtree_node, median_node, None, flag)
  File "C:\ufop\airbnb-data-collection\airbnb_survey.py", line 506, in recurse_quadtree
    (zoomable, median_leaf) = self.search_node(
                              ^^^^^^^^^^^^^^^^^
  File "C:\ufop\airbnb-data-collection\airbnb_survey.py", line 784, in search_node
    if listing.save(self.config.FLAGS_INSERT_NO_REPLACE):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ufop\airbnb-data-collection\airbnb_listing.py", line 167, in save
    self.config.connection.conn.rollback()
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'psycopg2.extensions.connection' object has no attribute 'conn'
2023-01-13 22:49:38,008 INFO    ======================================================================
2023-01-13 22:49:38,009 INFO    Survey 7, for Ouro Preto
2023-01-13 22:49:38,010 INFO    Searching by bounding box, max_zoom=24
2023-01-13 22:49:38,011 INFO    ----------------------------------------------------------------------
2023-01-13 22:49:38,011 INFO    Rectangle calculated: [-20.2519, -43.4372, -20.5229, -43.7846]
2023-01-13 22:49:38,011 INFO    Searching rectangle: zoom factor = 0, node = []
2023-01-13 22:49:38,436 WARNING HTTP status 403 from web site: IP address blocked. Waiting 1.0 minutes.
2023-01-13 22:50:40,042 ERROR   Exception in get_search_page_info_rectangle
Traceback (most recent call last):
  File "C:\ufop\airbnb-data-collection\airbnb_listing.py", line 157, in save
    self.__insert()
  File "C:\ufop\airbnb-data-collection\airbnb_listing.py", line 325, in __insert
    cur.execute(sql, insert_args)
psycopg2.errors.NumericValueOutOfRange: integer out of range


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\ufop\airbnb-data-collection\airbnb_survey.py", line 784, in search_node
    if listing.save(self.config.FLAGS_INSERT_NO_REPLACE):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ufop\airbnb-data-collection\airbnb_listing.py", line 167, in save
    self.config.connection.conn.rollback()
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'psycopg2.extensions.connection' object has no attribute 'conn'
2023-01-13 22:50:40,048 ERROR   Error in recurse_quadtree
Traceback (most recent call last):
  File "C:\ufop\airbnb-data-collection\airbnb_listing.py", line 157, in save
    self.__insert()
  File "C:\ufop\airbnb-data-collection\airbnb_listing.py", line 325, in __insert
    cur.execute(sql, insert_args)
psycopg2.errors.NumericValueOutOfRange: integer out of range


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\ufop\airbnb-data-collection\airbnb_survey.py", line 506, in recurse_quadtree
    (zoomable, median_leaf) = self.search_node(
                              ^^^^^^^^^^^^^^^^^
  File "C:\ufop\airbnb-data-collection\airbnb_survey.py", line 784, in search_node
    if listing.save(self.config.FLAGS_INSERT_NO_REPLACE):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ufop\airbnb-data-collection\airbnb_listing.py", line 167, in save
    self.config.connection.conn.rollback()
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'psycopg2.extensions.connection' object has no attribute 'conn'
2023-01-13 22:50:40,052 ERROR   Error
Traceback (most recent call last):
  File "C:\ufop\airbnb-data-collection\airbnb_listing.py", line 157, in save
    self.__insert()
  File "C:\ufop\airbnb-data-collection\airbnb_listing.py", line 325, in __insert
    cur.execute(sql, insert_args)
psycopg2.errors.NumericValueOutOfRange: integer out of range


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\ufop\airbnb-data-collection\airbnb_survey.py", line 445, in search
    self.recurse_quadtree(quadtree_node, median_node, None, flag)
  File "C:\ufop\airbnb-data-collection\airbnb_survey.py", line 506, in recurse_quadtree
    (zoomable, median_leaf) = self.search_node(
                              ^^^^^^^^^^^^^^^^^
  File "C:\ufop\airbnb-data-collection\airbnb_survey.py", line 784, in search_node
    if listing.save(self.config.FLAGS_INSERT_NO_REPLACE):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ufop\airbnb-data-collection\airbnb_listing.py", line 167, in save
    self.config.connection.conn.rollback()
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'psycopg2.extensions.connection' object has no attribute 'conn'
2023-01-13 22:52:47,619 INFO    ======================================================================
2023-01-13 22:52:47,620 INFO    Survey 7, for Ouro Preto
2023-01-13 22:52:47,621 INFO    Searching by bounding box, max_zoom=24
2023-01-13 22:52:47,622 INFO    ----------------------------------------------------------------------
2023-01-13 22:52:47,622 INFO    Rectangle calculated: [-20.2519, -43.4372, -20.5229, -43.7846]
2023-01-13 22:52:47,622 INFO    Searching rectangle: zoom factor = 0, node = []
2023-01-13 22:52:48,907 ERROR   Exception in get_search_page_info_rectangle
Traceback (most recent call last):
  File "C:\ufop\airbnb-data-collection\airbnb_listing.py", line 157, in save
    self.__insert()
  File "C:\ufop\airbnb-data-collection\airbnb_listing.py", line 325, in __insert
    cur.execute(sql, insert_args)
psycopg2.errors.SyntaxError: INSERT has more target columns than expressions
LINE 8: ...              property_type, currency, rate_type, avg_rating...
                                                             ^


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\ufop\airbnb-data-collection\airbnb_survey.py", line 784, in search_node
    if listing.save(self.config.FLAGS_INSERT_NO_REPLACE):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ufop\airbnb-data-collection\airbnb_listing.py", line 167, in save
    self.config.connection.conn.rollback()
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'psycopg2.extensions.connection' object has no attribute 'conn'
2023-01-13 22:52:48,928 ERROR   Error in recurse_quadtree
Traceback (most recent call last):
  File "C:\ufop\airbnb-data-collection\airbnb_listing.py", line 157, in save
    self.__insert()
  File "C:\ufop\airbnb-data-collection\airbnb_listing.py", line 325, in __insert
    cur.execute(sql, insert_args)
psycopg2.errors.SyntaxError: INSERT has more target columns than expressions
LINE 8: ...              property_type, currency, rate_type, avg_rating...
                                                             ^


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\ufop\airbnb-data-collection\airbnb_survey.py", line 506, in recurse_quadtree
    (zoomable, median_leaf) = self.search_node(
                              ^^^^^^^^^^^^^^^^^
  File "C:\ufop\airbnb-data-collection\airbnb_survey.py", line 784, in search_node
    if listing.save(self.config.FLAGS_INSERT_NO_REPLACE):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ufop\airbnb-data-collection\airbnb_listing.py", line 167, in save
    self.config.connection.conn.rollback()
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'psycopg2.extensions.connection' object has no attribute 'conn'
2023-01-13 22:52:48,940 ERROR   Error
Traceback (most recent call last):
  File "C:\ufop\airbnb-data-collection\airbnb_listing.py", line 157, in save
    self.__insert()
  File "C:\ufop\airbnb-data-collection\airbnb_listing.py", line 325, in __insert
    cur.execute(sql, insert_args)
psycopg2.errors.SyntaxError: INSERT has more target columns than expressions
LINE 8: ...              property_type, currency, rate_type, avg_rating...
                                                             ^


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\ufop\airbnb-data-collection\airbnb_survey.py", line 445, in search
    self.recurse_quadtree(quadtree_node, median_node, None, flag)
  File "C:\ufop\airbnb-data-collection\airbnb_survey.py", line 506, in recurse_quadtree
    (zoomable, median_leaf) = self.search_node(
                              ^^^^^^^^^^^^^^^^^
  File "C:\ufop\airbnb-data-collection\airbnb_survey.py", line 784, in search_node
    if listing.save(self.config.FLAGS_INSERT_NO_REPLACE):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ufop\airbnb-data-collection\airbnb_listing.py", line 167, in save
    self.config.connection.conn.rollback()
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'psycopg2.extensions.connection' object has no attribute 'conn'
2023-01-13 22:53:01,456 INFO    ======================================================================
2023-01-13 22:53:01,456 INFO    Survey 7, for Ouro Preto
2023-01-13 22:53:01,457 INFO    Searching by bounding box, max_zoom=24
2023-01-13 22:53:01,457 INFO    ----------------------------------------------------------------------
2023-01-13 22:53:01,458 INFO    Rectangle calculated: [-20.2519, -43.4372, -20.5229, -43.7846]
2023-01-13 22:53:01,458 INFO    Searching rectangle: zoom factor = 0, node = []
2023-01-13 22:53:01,759 WARNING HTTP status 403 from web site: IP address blocked. Waiting 1.0 minutes.
2023-01-13 22:54:03,023 WARNING HTTP status 403 from web site: IP address blocked. Waiting 1.0 minutes.
2023-01-13 22:55:04,459 ERROR   Exception saving room
2023-01-13 22:55:04,460 ERROR   Exception in get_search_page_info_rectangle
Traceback (most recent call last):
  File "C:\ufop\airbnb-data-collection\airbnb_survey.py", line 784, in search_node
    if listing.save(self.config.FLAGS_INSERT_NO_REPLACE):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ufop\airbnb-data-collection\airbnb_listing.py", line 157, in save
    self.__insert()
  File "C:\ufop\airbnb-data-collection\airbnb_listing.py", line 325, in __insert
    cur.execute(sql, insert_args)
TypeError: not all arguments converted during string formatting
2023-01-13 22:55:04,465 ERROR   TypeError in recurse_quadtree
Traceback (most recent call last):
  File "C:\ufop\airbnb-data-collection\airbnb_survey.py", line 506, in recurse_quadtree
    (zoomable, median_leaf) = self.search_node(
                              ^^^^^^^^^^^^^^^^^
  File "C:\ufop\airbnb-data-collection\airbnb_survey.py", line 784, in search_node
    if listing.save(self.config.FLAGS_INSERT_NO_REPLACE):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ufop\airbnb-data-collection\airbnb_listing.py", line 157, in save
    self.__insert()
  File "C:\ufop\airbnb-data-collection\airbnb_listing.py", line 325, in __insert
    cur.execute(sql, insert_args)
TypeError: not all arguments converted during string formatting
2023-01-13 22:55:04,467 ERROR   ('not all arguments converted during string formatting',)
2023-01-13 22:55:04,468 ERROR   Error
Traceback (most recent call last):
  File "C:\ufop\airbnb-data-collection\airbnb_survey.py", line 445, in search
    self.recurse_quadtree(quadtree_node, median_node, None, flag)
  File "C:\ufop\airbnb-data-collection\airbnb_survey.py", line 506, in recurse_quadtree
    (zoomable, median_leaf) = self.search_node(
                              ^^^^^^^^^^^^^^^^^
  File "C:\ufop\airbnb-data-collection\airbnb_survey.py", line 784, in search_node
    if listing.save(self.config.FLAGS_INSERT_NO_REPLACE):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ufop\airbnb-data-collection\airbnb_listing.py", line 157, in save
    self.__insert()
  File "C:\ufop\airbnb-data-collection\airbnb_listing.py", line 325, in __insert
    cur.execute(sql, insert_args)
TypeError: not all arguments converted during string formatting
2023-01-13 22:55:48,621 INFO    ======================================================================
2023-01-13 22:55:48,621 INFO    Survey 7, for Ouro Preto
2023-01-13 22:55:48,622 INFO    Searching by bounding box, max_zoom=24
2023-01-13 22:55:48,623 INFO    ----------------------------------------------------------------------
2023-01-13 22:55:48,623 INFO    Rectangle calculated: [-20.2519, -43.4372, -20.5229, -43.7846]
2023-01-13 22:55:48,624 INFO    Searching rectangle: zoom factor = 0, node = []
2023-01-13 22:55:51,246 ERROR   Exception in get_search_page_info_rectangle
Traceback (most recent call last):
  File "C:\ufop\airbnb-data-collection\airbnb_listing.py", line 157, in save
    self.__insert()
  File "C:\ufop\airbnb-data-collection\airbnb_listing.py", line 325, in __insert
    cur.execute(sql, insert_args)
psycopg2.errors.SyntaxError: INSERT has more target columns than expressions
LINE 8: ...              property_type, currency, rate_type, avg_rating...
                                                             ^


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\ufop\airbnb-data-collection\airbnb_survey.py", line 784, in search_node
    if listing.save(self.config.FLAGS_INSERT_NO_REPLACE):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ufop\airbnb-data-collection\airbnb_listing.py", line 167, in save
    self.config.connection.conn.rollback()
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'psycopg2.extensions.connection' object has no attribute 'conn'
2023-01-13 22:55:51,255 ERROR   Error in recurse_quadtree
Traceback (most recent call last):
  File "C:\ufop\airbnb-data-collection\airbnb_listing.py", line 157, in save
    self.__insert()
  File "C:\ufop\airbnb-data-collection\airbnb_listing.py", line 325, in __insert
    cur.execute(sql, insert_args)
psycopg2.errors.SyntaxError: INSERT has more target columns than expressions
LINE 8: ...              property_type, currency, rate_type, avg_rating...
                                                             ^


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\ufop\airbnb-data-collection\airbnb_survey.py", line 506, in recurse_quadtree
    (zoomable, median_leaf) = self.search_node(
                              ^^^^^^^^^^^^^^^^^
  File "C:\ufop\airbnb-data-collection\airbnb_survey.py", line 784, in search_node
    if listing.save(self.config.FLAGS_INSERT_NO_REPLACE):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ufop\airbnb-data-collection\airbnb_listing.py", line 167, in save
    self.config.connection.conn.rollback()
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'psycopg2.extensions.connection' object has no attribute 'conn'
2023-01-13 22:55:51,261 ERROR   Error
Traceback (most recent call last):
  File "C:\ufop\airbnb-data-collection\airbnb_listing.py", line 157, in save
    self.__insert()
  File "C:\ufop\airbnb-data-collection\airbnb_listing.py", line 325, in __insert
    cur.execute(sql, insert_args)
psycopg2.errors.SyntaxError: INSERT has more target columns than expressions
LINE 8: ...              property_type, currency, rate_type, avg_rating...
                                                             ^


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\ufop\airbnb-data-collection\airbnb_survey.py", line 445, in search
    self.recurse_quadtree(quadtree_node, median_node, None, flag)
  File "C:\ufop\airbnb-data-collection\airbnb_survey.py", line 506, in recurse_quadtree
    (zoomable, median_leaf) = self.search_node(
                              ^^^^^^^^^^^^^^^^^
  File "C:\ufop\airbnb-data-collection\airbnb_survey.py", line 784, in search_node
    if listing.save(self.config.FLAGS_INSERT_NO_REPLACE):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ufop\airbnb-data-collection\airbnb_listing.py", line 167, in save
    self.config.connection.conn.rollback()
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'psycopg2.extensions.connection' object has no attribute 'conn'
2023-01-13 22:56:13,267 INFO    ======================================================================
2023-01-13 22:56:13,268 INFO    Survey 7, for Ouro Preto
2023-01-13 22:56:13,270 INFO    Searching by bounding box, max_zoom=24
2023-01-13 22:56:13,271 INFO    ----------------------------------------------------------------------
2023-01-13 22:56:13,272 INFO    Rectangle calculated: [-20.2519, -43.4372, -20.5229, -43.7846]
2023-01-13 22:56:13,273 INFO    Searching rectangle: zoom factor = 0, node = []
2023-01-13 22:56:14,963 ERROR   Exception in get_search_page_info_rectangle
Traceback (most recent call last):
  File "C:\ufop\airbnb-data-collection\airbnb_listing.py", line 157, in save
    self.__insert()
  File "C:\ufop\airbnb-data-collection\airbnb_listing.py", line 325, in __insert
    cur.execute(sql, insert_args)
psycopg2.errors.SyntaxError: INSERT has more target columns than expressions
LINE 8: ...              property_type, currency, rate_type, avg_rating...
                                                             ^


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\ufop\airbnb-data-collection\airbnb_survey.py", line 784, in search_node
    if listing.save(self.config.FLAGS_INSERT_NO_REPLACE):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ufop\airbnb-data-collection\airbnb_listing.py", line 167, in save
    self.config.connection.conn.rollback()
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'psycopg2.extensions.connection' object has no attribute 'conn'
2023-01-13 22:56:14,968 ERROR   Error in recurse_quadtree
Traceback (most recent call last):
  File "C:\ufop\airbnb-data-collection\airbnb_listing.py", line 157, in save
    self.__insert()
  File "C:\ufop\airbnb-data-collection\airbnb_listing.py", line 325, in __insert
    cur.execute(sql, insert_args)
psycopg2.errors.SyntaxError: INSERT has more target columns than expressions
LINE 8: ...              property_type, currency, rate_type, avg_rating...
                                                             ^


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\ufop\airbnb-data-collection\airbnb_survey.py", line 506, in recurse_quadtree
    (zoomable, median_leaf) = self.search_node(
                              ^^^^^^^^^^^^^^^^^
  File "C:\ufop\airbnb-data-collection\airbnb_survey.py", line 784, in search_node
    if listing.save(self.config.FLAGS_INSERT_NO_REPLACE):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ufop\airbnb-data-collection\airbnb_listing.py", line 167, in save
    self.config.connection.conn.rollback()
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'psycopg2.extensions.connection' object has no attribute 'conn'
2023-01-13 22:56:14,971 ERROR   Error
Traceback (most recent call last):
  File "C:\ufop\airbnb-data-collection\airbnb_listing.py", line 157, in save
    self.__insert()
  File "C:\ufop\airbnb-data-collection\airbnb_listing.py", line 325, in __insert
    cur.execute(sql, insert_args)
psycopg2.errors.SyntaxError: INSERT has more target columns than expressions
LINE 8: ...              property_type, currency, rate_type, avg_rating...
                                                             ^


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\ufop\airbnb-data-collection\airbnb_survey.py", line 445, in search
    self.recurse_quadtree(quadtree_node, median_node, None, flag)
  File "C:\ufop\airbnb-data-collection\airbnb_survey.py", line 506, in recurse_quadtree
    (zoomable, median_leaf) = self.search_node(
                              ^^^^^^^^^^^^^^^^^
  File "C:\ufop\airbnb-data-collection\airbnb_survey.py", line 784, in search_node
    if listing.save(self.config.FLAGS_INSERT_NO_REPLACE):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ufop\airbnb-data-collection\airbnb_listing.py", line 167, in save
    self.config.connection.conn.rollback()
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'psycopg2.extensions.connection' object has no attribute 'conn'
2023-01-13 22:57:13,713 INFO    ======================================================================
2023-01-13 22:57:13,714 INFO    Survey 7, for Ouro Preto
2023-01-13 22:57:13,714 INFO    Searching by bounding box, max_zoom=24
2023-01-13 22:57:13,715 INFO    ----------------------------------------------------------------------
2023-01-13 22:57:13,715 INFO    Rectangle calculated: [-20.2519, -43.4372, -20.5229, -43.7846]
2023-01-13 22:57:13,716 INFO    Searching rectangle: zoom factor = 0, node = []
2023-01-13 22:57:15,550 ERROR   Exception in get_search_page_info_rectangle
Traceback (most recent call last):
  File "C:\ufop\airbnb-data-collection\airbnb_listing.py", line 157, in save
    self.__insert()
  File "C:\ufop\airbnb-data-collection\airbnb_listing.py", line 325, in __insert
    cur.execute(sql, insert_args)
psycopg2.errors.NumericValueOutOfRange: integer out of range


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\ufop\airbnb-data-collection\airbnb_survey.py", line 784, in search_node
    if listing.save(self.config.FLAGS_INSERT_NO_REPLACE):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ufop\airbnb-data-collection\airbnb_listing.py", line 167, in save
    self.config.connection.conn.rollback()
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'psycopg2.extensions.connection' object has no attribute 'conn'
2023-01-13 22:57:15,556 ERROR   Error in recurse_quadtree
Traceback (most recent call last):
  File "C:\ufop\airbnb-data-collection\airbnb_listing.py", line 157, in save
    self.__insert()
  File "C:\ufop\airbnb-data-collection\airbnb_listing.py", line 325, in __insert
    cur.execute(sql, insert_args)
psycopg2.errors.NumericValueOutOfRange: integer out of range


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\ufop\airbnb-data-collection\airbnb_survey.py", line 506, in recurse_quadtree
    (zoomable, median_leaf) = self.search_node(
                              ^^^^^^^^^^^^^^^^^
  File "C:\ufop\airbnb-data-collection\airbnb_survey.py", line 784, in search_node
    if listing.save(self.config.FLAGS_INSERT_NO_REPLACE):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ufop\airbnb-data-collection\airbnb_listing.py", line 167, in save
    self.config.connection.conn.rollback()
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'psycopg2.extensions.connection' object has no attribute 'conn'
2023-01-13 22:57:15,561 ERROR   Error
Traceback (most recent call last):
  File "C:\ufop\airbnb-data-collection\airbnb_listing.py", line 157, in save
    self.__insert()
  File "C:\ufop\airbnb-data-collection\airbnb_listing.py", line 325, in __insert
    cur.execute(sql, insert_args)
psycopg2.errors.NumericValueOutOfRange: integer out of range


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\ufop\airbnb-data-collection\airbnb_survey.py", line 445, in search
    self.recurse_quadtree(quadtree_node, median_node, None, flag)
  File "C:\ufop\airbnb-data-collection\airbnb_survey.py", line 506, in recurse_quadtree
    (zoomable, median_leaf) = self.search_node(
                              ^^^^^^^^^^^^^^^^^
  File "C:\ufop\airbnb-data-collection\airbnb_survey.py", line 784, in search_node
    if listing.save(self.config.FLAGS_INSERT_NO_REPLACE):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ufop\airbnb-data-collection\airbnb_listing.py", line 167, in save
    self.config.connection.conn.rollback()
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'psycopg2.extensions.connection' object has no attribute 'conn'
2023-01-13 22:57:56,284 INFO    ======================================================================
2023-01-13 22:57:56,285 INFO    Survey 7, for Ouro Preto
2023-01-13 22:57:56,286 INFO    Searching by bounding box, max_zoom=24
2023-01-13 22:57:56,286 INFO    ----------------------------------------------------------------------
2023-01-13 22:57:56,287 INFO    Rectangle calculated: [-20.2519, -43.4372, -20.5229, -43.7846]
2023-01-13 22:57:56,287 INFO    Searching rectangle: zoom factor = 0, node = []
2023-01-13 22:57:56,477 WARNING HTTP status 403 from web site: IP address blocked. Waiting 1.0 minutes.
2023-01-13 22:58:57,644 WARNING HTTP status 403 from web site: IP address blocked. Waiting 1.0 minutes.
2023-01-13 22:59:58,959 ERROR   Exception in get_search_page_info_rectangle
Traceback (most recent call last):
  File "C:\ufop\airbnb-data-collection\airbnb_listing.py", line 157, in save
    self.__insert()
  File "C:\ufop\airbnb-data-collection\airbnb_listing.py", line 325, in __insert
    cur.execute(sql, insert_args)
psycopg2.errors.NumericValueOutOfRange: integer out of range


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\ufop\airbnb-data-collection\airbnb_survey.py", line 784, in search_node
    if listing.save(self.config.FLAGS_INSERT_NO_REPLACE):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ufop\airbnb-data-collection\airbnb_listing.py", line 167, in save
    self.config.connection.conn.rollback()
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'psycopg2.extensions.connection' object has no attribute 'conn'
2023-01-13 22:59:58,968 ERROR   Error in recurse_quadtree
Traceback (most recent call last):
  File "C:\ufop\airbnb-data-collection\airbnb_listing.py", line 157, in save
    self.__insert()
  File "C:\ufop\airbnb-data-collection\airbnb_listing.py", line 325, in __insert
    cur.execute(sql, insert_args)
psycopg2.errors.NumericValueOutOfRange: integer out of range


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\ufop\airbnb-data-collection\airbnb_survey.py", line 506, in recurse_quadtree
    (zoomable, median_leaf) = self.search_node(
                              ^^^^^^^^^^^^^^^^^
  File "C:\ufop\airbnb-data-collection\airbnb_survey.py", line 784, in search_node
    if listing.save(self.config.FLAGS_INSERT_NO_REPLACE):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ufop\airbnb-data-collection\airbnb_listing.py", line 167, in save
    self.config.connection.conn.rollback()
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'psycopg2.extensions.connection' object has no attribute 'conn'
2023-01-13 22:59:58,976 ERROR   Error
Traceback (most recent call last):
  File "C:\ufop\airbnb-data-collection\airbnb_listing.py", line 157, in save
    self.__insert()
  File "C:\ufop\airbnb-data-collection\airbnb_listing.py", line 325, in __insert
    cur.execute(sql, insert_args)
psycopg2.errors.NumericValueOutOfRange: integer out of range


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\ufop\airbnb-data-collection\airbnb_survey.py", line 445, in search
    self.recurse_quadtree(quadtree_node, median_node, None, flag)
  File "C:\ufop\airbnb-data-collection\airbnb_survey.py", line 506, in recurse_quadtree
    (zoomable, median_leaf) = self.search_node(
                              ^^^^^^^^^^^^^^^^^
  File "C:\ufop\airbnb-data-collection\airbnb_survey.py", line 784, in search_node
    if listing.save(self.config.FLAGS_INSERT_NO_REPLACE):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ufop\airbnb-data-collection\airbnb_listing.py", line 167, in save
    self.config.connection.conn.rollback()
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'psycopg2.extensions.connection' object has no attribute 'conn'
2023-01-13 23:07:51,281 INFO    ======================================================================
2023-01-13 23:07:51,281 INFO    Survey 7, for Ouro Preto
2023-01-13 23:07:51,283 INFO    Searching by bounding box, max_zoom=24
2023-01-13 23:07:51,283 INFO    ----------------------------------------------------------------------
2023-01-13 23:07:51,284 INFO    Rectangle calculated: [-20.2519, -43.4372, -20.5229, -43.7846]
2023-01-13 23:07:51,284 INFO    Searching rectangle: zoom factor = 0, node = []
2023-01-13 23:07:51,788 WARNING HTTP status 403 from web site: IP address blocked. Waiting 1.0 minutes.
2023-01-13 23:08:54,295 INFO    Room 42158217: insert failed
2023-01-13 23:08:54,307 INFO    Room 47939876: insert failed
2023-01-13 23:08:54,317 INFO    Room 52024666: insert failed
2023-01-13 23:08:54,324 INFO    Room 51978370: insert failed
2023-01-13 23:08:54,331 INFO    Room 40752066: insert failed
2023-01-13 23:08:54,337 INFO    Room 41502392: insert failed
2023-01-13 23:08:54,359 INFO    Room 30403033: insert failed
2023-01-13 23:08:54,369 INFO    Room 40172480: insert failed
2023-01-13 23:08:54,390 INFO    Room 47334727: insert failed
2023-01-13 23:08:54,396 INFO    Room 54222723: insert failed
2023-01-13 23:08:54,401 INFO    Room 50723507: insert failed
2023-01-13 23:08:54,418 ERROR   Exception in get_search_page_info_rectangle
Traceback (most recent call last):
  File "C:\ufop\airbnb-data-collection\airbnb_listing.py", line 157, in save
    self.__insert()
  File "C:\ufop\airbnb-data-collection\airbnb_listing.py", line 325, in __insert
    cur.execute(sql, insert_args)
psycopg2.errors.NumericValueOutOfRange: integer out of range


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\ufop\airbnb-data-collection\airbnb_survey.py", line 784, in search_node
    if listing.save(self.config.FLAGS_INSERT_NO_REPLACE):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ufop\airbnb-data-collection\airbnb_listing.py", line 167, in save
    self.config.connection.conn.rollback()
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'psycopg2.extensions.connection' object has no attribute 'conn'
2023-01-13 23:08:54,432 ERROR   Error in recurse_quadtree
Traceback (most recent call last):
  File "C:\ufop\airbnb-data-collection\airbnb_listing.py", line 157, in save
    self.__insert()
  File "C:\ufop\airbnb-data-collection\airbnb_listing.py", line 325, in __insert
    cur.execute(sql, insert_args)
psycopg2.errors.NumericValueOutOfRange: integer out of range


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\ufop\airbnb-data-collection\airbnb_survey.py", line 506, in recurse_quadtree
    (zoomable, median_leaf) = self.search_node(
                              ^^^^^^^^^^^^^^^^^
  File "C:\ufop\airbnb-data-collection\airbnb_survey.py", line 784, in search_node
    if listing.save(self.config.FLAGS_INSERT_NO_REPLACE):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ufop\airbnb-data-collection\airbnb_listing.py", line 167, in save
    self.config.connection.conn.rollback()
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'psycopg2.extensions.connection' object has no attribute 'conn'
2023-01-13 23:08:54,439 ERROR   Error
Traceback (most recent call last):
  File "C:\ufop\airbnb-data-collection\airbnb_listing.py", line 157, in save
    self.__insert()
  File "C:\ufop\airbnb-data-collection\airbnb_listing.py", line 325, in __insert
    cur.execute(sql, insert_args)
psycopg2.errors.NumericValueOutOfRange: integer out of range


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\ufop\airbnb-data-collection\airbnb_survey.py", line 445, in search
    self.recurse_quadtree(quadtree_node, median_node, None, flag)
  File "C:\ufop\airbnb-data-collection\airbnb_survey.py", line 506, in recurse_quadtree
    (zoomable, median_leaf) = self.search_node(
                              ^^^^^^^^^^^^^^^^^
  File "C:\ufop\airbnb-data-collection\airbnb_survey.py", line 784, in search_node
    if listing.save(self.config.FLAGS_INSERT_NO_REPLACE):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ufop\airbnb-data-collection\airbnb_listing.py", line 167, in save
    self.config.connection.conn.rollback()
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'psycopg2.extensions.connection' object has no attribute 'conn'
2023-01-13 23:10:15,614 INFO    ======================================================================
2023-01-13 23:10:15,615 INFO    Survey 7, for Ouro Preto
2023-01-13 23:10:15,617 INFO    Searching by bounding box, max_zoom=24
2023-01-13 23:10:15,618 INFO    ----------------------------------------------------------------------
2023-01-13 23:10:15,619 INFO    Rectangle calculated: [-20.2519, -43.4372, -20.5229, -43.7846]
2023-01-13 23:10:15,620 INFO    Searching rectangle: zoom factor = 0, node = []
2023-01-13 23:10:17,300 INFO    Room 42158217: insert failed
2023-01-13 23:10:17,305 INFO    Room 47939876: insert failed
2023-01-13 23:10:17,311 INFO    Room 52024666: insert failed
2023-01-13 23:10:17,316 INFO    Room 51978370: insert failed
2023-01-13 23:10:17,320 INFO    Room 40752066: insert failed
2023-01-13 23:10:17,324 INFO    Room 41502392: insert failed
2023-01-13 23:10:17,344 INFO    Room 30403033: insert failed
2023-01-13 23:10:17,355 INFO    Room 40172480: insert failed
2023-01-13 23:10:17,365 INFO    Room 47334727: insert failed
2023-01-13 23:10:17,379 INFO    Room 54222723: insert failed
2023-01-13 23:10:17,385 INFO    Room 50723507: insert failed
2023-01-13 23:10:17,391 ERROR   Exception in get_search_page_info_rectangle
Traceback (most recent call last):
  File "C:\ufop\airbnb-data-collection\airbnb_listing.py", line 157, in save
    self.__insert()
  File "C:\ufop\airbnb-data-collection\airbnb_listing.py", line 326, in __insert
    cur.execute(sql, insert_args)
psycopg2.errors.NumericValueOutOfRange: integer out of range


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\ufop\airbnb-data-collection\airbnb_survey.py", line 784, in search_node
    if listing.save(self.config.FLAGS_INSERT_NO_REPLACE):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ufop\airbnb-data-collection\airbnb_listing.py", line 167, in save
    self.config.connection.conn.rollback()
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'psycopg2.extensions.connection' object has no attribute 'conn'
2023-01-13 23:10:17,395 ERROR   Error in recurse_quadtree
Traceback (most recent call last):
  File "C:\ufop\airbnb-data-collection\airbnb_listing.py", line 157, in save
    self.__insert()
  File "C:\ufop\airbnb-data-collection\airbnb_listing.py", line 326, in __insert
    cur.execute(sql, insert_args)
psycopg2.errors.NumericValueOutOfRange: integer out of range


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\ufop\airbnb-data-collection\airbnb_survey.py", line 506, in recurse_quadtree
    (zoomable, median_leaf) = self.search_node(
                              ^^^^^^^^^^^^^^^^^
  File "C:\ufop\airbnb-data-collection\airbnb_survey.py", line 784, in search_node
    if listing.save(self.config.FLAGS_INSERT_NO_REPLACE):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ufop\airbnb-data-collection\airbnb_listing.py", line 167, in save
    self.config.connection.conn.rollback()
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'psycopg2.extensions.connection' object has no attribute 'conn'
2023-01-13 23:10:17,415 ERROR   Error
Traceback (most recent call last):
  File "C:\ufop\airbnb-data-collection\airbnb_listing.py", line 157, in save
    self.__insert()
  File "C:\ufop\airbnb-data-collection\airbnb_listing.py", line 326, in __insert
    cur.execute(sql, insert_args)
psycopg2.errors.NumericValueOutOfRange: integer out of range


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\ufop\airbnb-data-collection\airbnb_survey.py", line 445, in search
    self.recurse_quadtree(quadtree_node, median_node, None, flag)
  File "C:\ufop\airbnb-data-collection\airbnb_survey.py", line 506, in recurse_quadtree
    (zoomable, median_leaf) = self.search_node(
                              ^^^^^^^^^^^^^^^^^
  File "C:\ufop\airbnb-data-collection\airbnb_survey.py", line 784, in search_node
    if listing.save(self.config.FLAGS_INSERT_NO_REPLACE):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ufop\airbnb-data-collection\airbnb_listing.py", line 167, in save
    self.config.connection.conn.rollback()
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'psycopg2.extensions.connection' object has no attribute 'conn'
2023-01-13 23:11:18,907 INFO    ======================================================================
2023-01-13 23:11:18,908 INFO    Survey 7, for Ouro Preto
2023-01-13 23:11:18,908 INFO    Searching by bounding box, max_zoom=24
2023-01-13 23:11:18,910 INFO    ----------------------------------------------------------------------
2023-01-13 23:11:18,910 INFO    Rectangle calculated: [-20.2519, -43.4372, -20.5229, -43.7846]
2023-01-13 23:11:18,910 INFO    Searching rectangle: zoom factor = 0, node = []
2023-01-13 23:11:19,380 WARNING HTTP status 403 from web site: IP address blocked. Waiting 1.0 minutes.
2023-01-13 23:12:20,491 ERROR   Exception saving room
2023-01-13 23:12:20,492 ERROR   Exception in get_search_page_info_rectangle
Traceback (most recent call last):
  File "C:\ufop\airbnb-data-collection\airbnb_survey.py", line 784, in search_node
    if listing.save(self.config.FLAGS_INSERT_NO_REPLACE):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ufop\airbnb-data-collection\airbnb_listing.py", line 157, in save
    self.__insert()
  File "C:\ufop\airbnb-data-collection\airbnb_listing.py", line 326, in __insert
    cur.execute(sql, insert_args)
TypeError: not all arguments converted during string formatting
2023-01-13 23:12:20,501 ERROR   TypeError in recurse_quadtree
Traceback (most recent call last):
  File "C:\ufop\airbnb-data-collection\airbnb_survey.py", line 506, in recurse_quadtree
    (zoomable, median_leaf) = self.search_node(
                              ^^^^^^^^^^^^^^^^^
  File "C:\ufop\airbnb-data-collection\airbnb_survey.py", line 784, in search_node
    if listing.save(self.config.FLAGS_INSERT_NO_REPLACE):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ufop\airbnb-data-collection\airbnb_listing.py", line 157, in save
    self.__insert()
  File "C:\ufop\airbnb-data-collection\airbnb_listing.py", line 326, in __insert
    cur.execute(sql, insert_args)
TypeError: not all arguments converted during string formatting
2023-01-13 23:12:20,506 ERROR   ('not all arguments converted during string formatting',)
2023-01-13 23:12:20,507 ERROR   Error
Traceback (most recent call last):
  File "C:\ufop\airbnb-data-collection\airbnb_survey.py", line 445, in search
    self.recurse_quadtree(quadtree_node, median_node, None, flag)
  File "C:\ufop\airbnb-data-collection\airbnb_survey.py", line 506, in recurse_quadtree
    (zoomable, median_leaf) = self.search_node(
                              ^^^^^^^^^^^^^^^^^
  File "C:\ufop\airbnb-data-collection\airbnb_survey.py", line 784, in search_node
    if listing.save(self.config.FLAGS_INSERT_NO_REPLACE):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ufop\airbnb-data-collection\airbnb_listing.py", line 157, in save
    self.__insert()
  File "C:\ufop\airbnb-data-collection\airbnb_listing.py", line 326, in __insert
    cur.execute(sql, insert_args)
TypeError: not all arguments converted during string formatting
2023-01-13 23:12:37,685 INFO    ======================================================================
2023-01-13 23:12:37,685 INFO    Survey 7, for Ouro Preto
2023-01-13 23:12:37,686 INFO    Searching by bounding box, max_zoom=24
2023-01-13 23:12:37,687 INFO    ----------------------------------------------------------------------
2023-01-13 23:12:37,687 INFO    Rectangle calculated: [-20.2519, -43.4372, -20.5229, -43.7846]
2023-01-13 23:12:37,688 INFO    Searching rectangle: zoom factor = 0, node = []
2023-01-13 23:12:38,960 ERROR   Exception in get_search_page_info_rectangle
Traceback (most recent call last):
  File "C:\ufop\airbnb-data-collection\airbnb_listing.py", line 157, in save
    self.__insert()
  File "C:\ufop\airbnb-data-collection\airbnb_listing.py", line 326, in __insert
    cur.execute(sql, insert_args)
psycopg2.errors.NumericValueOutOfRange: integer out of range


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\ufop\airbnb-data-collection\airbnb_survey.py", line 784, in search_node
    if listing.save(self.config.FLAGS_INSERT_NO_REPLACE):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ufop\airbnb-data-collection\airbnb_listing.py", line 167, in save
    self.config.connection.conn.rollback()
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'psycopg2.extensions.connection' object has no attribute 'conn'
2023-01-13 23:12:38,985 ERROR   Error in recurse_quadtree
Traceback (most recent call last):
  File "C:\ufop\airbnb-data-collection\airbnb_listing.py", line 157, in save
    self.__insert()
  File "C:\ufop\airbnb-data-collection\airbnb_listing.py", line 326, in __insert
    cur.execute(sql, insert_args)
psycopg2.errors.NumericValueOutOfRange: integer out of range


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\ufop\airbnb-data-collection\airbnb_survey.py", line 506, in recurse_quadtree
    (zoomable, median_leaf) = self.search_node(
                              ^^^^^^^^^^^^^^^^^
  File "C:\ufop\airbnb-data-collection\airbnb_survey.py", line 784, in search_node
    if listing.save(self.config.FLAGS_INSERT_NO_REPLACE):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ufop\airbnb-data-collection\airbnb_listing.py", line 167, in save
    self.config.connection.conn.rollback()
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'psycopg2.extensions.connection' object has no attribute 'conn'
2023-01-13 23:12:38,994 ERROR   Error
Traceback (most recent call last):
  File "C:\ufop\airbnb-data-collection\airbnb_listing.py", line 157, in save
    self.__insert()
  File "C:\ufop\airbnb-data-collection\airbnb_listing.py", line 326, in __insert
    cur.execute(sql, insert_args)
psycopg2.errors.NumericValueOutOfRange: integer out of range


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\ufop\airbnb-data-collection\airbnb_survey.py", line 445, in search
    self.recurse_quadtree(quadtree_node, median_node, None, flag)
  File "C:\ufop\airbnb-data-collection\airbnb_survey.py", line 506, in recurse_quadtree
    (zoomable, median_leaf) = self.search_node(
                              ^^^^^^^^^^^^^^^^^
  File "C:\ufop\airbnb-data-collection\airbnb_survey.py", line 784, in search_node
    if listing.save(self.config.FLAGS_INSERT_NO_REPLACE):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ufop\airbnb-data-collection\airbnb_listing.py", line 167, in save
    self.config.connection.conn.rollback()
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'psycopg2.extensions.connection' object has no attribute 'conn'
2023-01-13 23:13:06,508 INFO    ======================================================================
2023-01-13 23:13:06,511 INFO    Survey 7, for Ouro Preto
2023-01-13 23:13:06,518 INFO    Searching by bounding box, max_zoom=24
2023-01-13 23:13:06,520 INFO    ----------------------------------------------------------------------
2023-01-13 23:13:06,522 INFO    Rectangle calculated: [-20.2519, -43.4372, -20.5229, -43.7846]
2023-01-13 23:13:06,523 INFO    Searching rectangle: zoom factor = 0, node = []
2023-01-13 23:13:07,873 ERROR   Exception in get_search_page_info_rectangle
Traceback (most recent call last):
  File "C:\ufop\airbnb-data-collection\airbnb_listing.py", line 157, in save
    self.__insert()
  File "C:\ufop\airbnb-data-collection\airbnb_listing.py", line 319, in __insert
    cur.execute(sql, insert_args)
psycopg2.errors.UndefinedColumn: column "minsta" of relation "room" does not exist
LINE 5:                 bathrooms, minsta)
                                   ^


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\ufop\airbnb-data-collection\airbnb_survey.py", line 784, in search_node
    if listing.save(self.config.FLAGS_INSERT_NO_REPLACE):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ufop\airbnb-data-collection\airbnb_listing.py", line 167, in save
    self.config.connection.conn.rollback()
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'psycopg2.extensions.connection' object has no attribute 'conn'
2023-01-13 23:13:07,879 ERROR   Error in recurse_quadtree
Traceback (most recent call last):
  File "C:\ufop\airbnb-data-collection\airbnb_listing.py", line 157, in save
    self.__insert()
  File "C:\ufop\airbnb-data-collection\airbnb_listing.py", line 319, in __insert
    cur.execute(sql, insert_args)
psycopg2.errors.UndefinedColumn: column "minsta" of relation "room" does not exist
LINE 5:                 bathrooms, minsta)
                                   ^


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\ufop\airbnb-data-collection\airbnb_survey.py", line 506, in recurse_quadtree
    (zoomable, median_leaf) = self.search_node(
                              ^^^^^^^^^^^^^^^^^
  File "C:\ufop\airbnb-data-collection\airbnb_survey.py", line 784, in search_node
    if listing.save(self.config.FLAGS_INSERT_NO_REPLACE):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ufop\airbnb-data-collection\airbnb_listing.py", line 167, in save
    self.config.connection.conn.rollback()
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'psycopg2.extensions.connection' object has no attribute 'conn'
2023-01-13 23:13:07,883 ERROR   Error
Traceback (most recent call last):
  File "C:\ufop\airbnb-data-collection\airbnb_listing.py", line 157, in save
    self.__insert()
  File "C:\ufop\airbnb-data-collection\airbnb_listing.py", line 319, in __insert
    cur.execute(sql, insert_args)
psycopg2.errors.UndefinedColumn: column "minsta" of relation "room" does not exist
LINE 5:                 bathrooms, minsta)
                                   ^


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\ufop\airbnb-data-collection\airbnb_survey.py", line 445, in search
    self.recurse_quadtree(quadtree_node, median_node, None, flag)
  File "C:\ufop\airbnb-data-collection\airbnb_survey.py", line 506, in recurse_quadtree
    (zoomable, median_leaf) = self.search_node(
                              ^^^^^^^^^^^^^^^^^
  File "C:\ufop\airbnb-data-collection\airbnb_survey.py", line 784, in search_node
    if listing.save(self.config.FLAGS_INSERT_NO_REPLACE):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ufop\airbnb-data-collection\airbnb_listing.py", line 167, in save
    self.config.connection.conn.rollback()
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'psycopg2.extensions.connection' object has no attribute 'conn'
2023-01-13 23:13:17,246 INFO    ======================================================================
2023-01-13 23:13:17,246 INFO    Survey 7, for Ouro Preto
2023-01-13 23:13:17,247 INFO    Searching by bounding box, max_zoom=24
2023-01-13 23:13:17,247 INFO    ----------------------------------------------------------------------
2023-01-13 23:13:17,248 INFO    Rectangle calculated: [-20.2519, -43.4372, -20.5229, -43.7846]
2023-01-13 23:13:17,248 INFO    Searching rectangle: zoom factor = 0, node = []
2023-01-13 23:13:18,806 ERROR   Exception in get_search_page_info_rectangle
Traceback (most recent call last):
  File "C:\ufop\airbnb-data-collection\airbnb_listing.py", line 157, in save
    self.__insert()
  File "C:\ufop\airbnb-data-collection\airbnb_listing.py", line 319, in __insert
    cur.execute(sql, insert_args)
psycopg2.errors.NumericValueOutOfRange: integer out of range


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\ufop\airbnb-data-collection\airbnb_survey.py", line 784, in search_node
    if listing.save(self.config.FLAGS_INSERT_NO_REPLACE):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ufop\airbnb-data-collection\airbnb_listing.py", line 167, in save
    self.config.connection.conn.rollback()
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'psycopg2.extensions.connection' object has no attribute 'conn'
2023-01-13 23:13:18,813 ERROR   Error in recurse_quadtree
Traceback (most recent call last):
  File "C:\ufop\airbnb-data-collection\airbnb_listing.py", line 157, in save
    self.__insert()
  File "C:\ufop\airbnb-data-collection\airbnb_listing.py", line 319, in __insert
    cur.execute(sql, insert_args)
psycopg2.errors.NumericValueOutOfRange: integer out of range


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\ufop\airbnb-data-collection\airbnb_survey.py", line 506, in recurse_quadtree
    (zoomable, median_leaf) = self.search_node(
                              ^^^^^^^^^^^^^^^^^
  File "C:\ufop\airbnb-data-collection\airbnb_survey.py", line 784, in search_node
    if listing.save(self.config.FLAGS_INSERT_NO_REPLACE):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ufop\airbnb-data-collection\airbnb_listing.py", line 167, in save
    self.config.connection.conn.rollback()
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'psycopg2.extensions.connection' object has no attribute 'conn'
2023-01-13 23:13:18,817 ERROR   Error
Traceback (most recent call last):
  File "C:\ufop\airbnb-data-collection\airbnb_listing.py", line 157, in save
    self.__insert()
  File "C:\ufop\airbnb-data-collection\airbnb_listing.py", line 319, in __insert
    cur.execute(sql, insert_args)
psycopg2.errors.NumericValueOutOfRange: integer out of range


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\ufop\airbnb-data-collection\airbnb_survey.py", line 445, in search
    self.recurse_quadtree(quadtree_node, median_node, None, flag)
  File "C:\ufop\airbnb-data-collection\airbnb_survey.py", line 506, in recurse_quadtree
    (zoomable, median_leaf) = self.search_node(
                              ^^^^^^^^^^^^^^^^^
  File "C:\ufop\airbnb-data-collection\airbnb_survey.py", line 784, in search_node
    if listing.save(self.config.FLAGS_INSERT_NO_REPLACE):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ufop\airbnb-data-collection\airbnb_listing.py", line 167, in save
    self.config.connection.conn.rollback()
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'psycopg2.extensions.connection' object has no attribute 'conn'
2023-01-13 23:13:45,719 INFO    ======================================================================
2023-01-13 23:13:45,720 INFO    Survey 7, for Ouro Preto
2023-01-13 23:13:45,720 INFO    Searching by bounding box, max_zoom=24
2023-01-13 23:13:45,721 INFO    ----------------------------------------------------------------------
2023-01-13 23:13:45,721 INFO    Rectangle calculated: [-20.2519, -43.4372, -20.5229, -43.7846]
2023-01-13 23:13:45,722 INFO    Searching rectangle: zoom factor = 0, node = []
2023-01-13 23:13:47,224 ERROR   Exception in get_search_page_info_rectangle
Traceback (most recent call last):
  File "C:\ufop\airbnb-data-collection\airbnb_listing.py", line 157, in save
    self.__insert()
  File "C:\ufop\airbnb-data-collection\airbnb_listing.py", line 314, in __insert
    cur.execute(sql, insert_args)
psycopg2.errors.NumericValueOutOfRange: integer out of range


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\ufop\airbnb-data-collection\airbnb_survey.py", line 784, in search_node
    if listing.save(self.config.FLAGS_INSERT_NO_REPLACE):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ufop\airbnb-data-collection\airbnb_listing.py", line 167, in save
    self.config.connection.conn.rollback()
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'psycopg2.extensions.connection' object has no attribute 'conn'
2023-01-13 23:13:47,230 ERROR   Error in recurse_quadtree
Traceback (most recent call last):
  File "C:\ufop\airbnb-data-collection\airbnb_listing.py", line 157, in save
    self.__insert()
  File "C:\ufop\airbnb-data-collection\airbnb_listing.py", line 314, in __insert
    cur.execute(sql, insert_args)
psycopg2.errors.NumericValueOutOfRange: integer out of range


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\ufop\airbnb-data-collection\airbnb_survey.py", line 506, in recurse_quadtree
    (zoomable, median_leaf) = self.search_node(
                              ^^^^^^^^^^^^^^^^^
  File "C:\ufop\airbnb-data-collection\airbnb_survey.py", line 784, in search_node
    if listing.save(self.config.FLAGS_INSERT_NO_REPLACE):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ufop\airbnb-data-collection\airbnb_listing.py", line 167, in save
    self.config.connection.conn.rollback()
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'psycopg2.extensions.connection' object has no attribute 'conn'
2023-01-13 23:13:47,235 ERROR   Error
Traceback (most recent call last):
  File "C:\ufop\airbnb-data-collection\airbnb_listing.py", line 157, in save
    self.__insert()
  File "C:\ufop\airbnb-data-collection\airbnb_listing.py", line 314, in __insert
    cur.execute(sql, insert_args)
psycopg2.errors.NumericValueOutOfRange: integer out of range


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\ufop\airbnb-data-collection\airbnb_survey.py", line 445, in search
    self.recurse_quadtree(quadtree_node, median_node, None, flag)
  File "C:\ufop\airbnb-data-collection\airbnb_survey.py", line 506, in recurse_quadtree
    (zoomable, median_leaf) = self.search_node(
                              ^^^^^^^^^^^^^^^^^
  File "C:\ufop\airbnb-data-collection\airbnb_survey.py", line 784, in search_node
    if listing.save(self.config.FLAGS_INSERT_NO_REPLACE):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ufop\airbnb-data-collection\airbnb_listing.py", line 167, in save
    self.config.connection.conn.rollback()
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'psycopg2.extensions.connection' object has no attribute 'conn'
2023-01-13 23:14:06,473 INFO    ======================================================================
2023-01-13 23:14:06,474 INFO    Survey 7, for Ouro Preto
2023-01-13 23:14:06,476 INFO    Searching by bounding box, max_zoom=24
2023-01-13 23:14:06,477 INFO    ----------------------------------------------------------------------
2023-01-13 23:14:06,478 INFO    Rectangle calculated: [-20.2519, -43.4372, -20.5229, -43.7846]
2023-01-13 23:14:06,478 INFO    Searching rectangle: zoom factor = 0, node = []
2023-01-13 23:14:08,869 ERROR   Exception in get_search_page_info_rectangle
Traceback (most recent call last):
  File "C:\ufop\airbnb-data-collection\airbnb_listing.py", line 157, in save
    self.__insert()
  File "C:\ufop\airbnb-data-collection\airbnb_listing.py", line 314, in __insert
    cur.execute(sql, insert_args)
psycopg2.errors.NumericValueOutOfRange: integer out of range


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\ufop\airbnb-data-collection\airbnb_survey.py", line 784, in search_node
    if listing.save(self.config.FLAGS_INSERT_NO_REPLACE):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ufop\airbnb-data-collection\airbnb_listing.py", line 167, in save
    self.config.connection.conn.rollback()
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'psycopg2.extensions.connection' object has no attribute 'conn'
2023-01-13 23:14:08,873 ERROR   Error in recurse_quadtree
Traceback (most recent call last):
  File "C:\ufop\airbnb-data-collection\airbnb_listing.py", line 157, in save
    self.__insert()
  File "C:\ufop\airbnb-data-collection\airbnb_listing.py", line 314, in __insert
    cur.execute(sql, insert_args)
psycopg2.errors.NumericValueOutOfRange: integer out of range


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\ufop\airbnb-data-collection\airbnb_survey.py", line 506, in recurse_quadtree
    (zoomable, median_leaf) = self.search_node(
                              ^^^^^^^^^^^^^^^^^
  File "C:\ufop\airbnb-data-collection\airbnb_survey.py", line 784, in search_node
    if listing.save(self.config.FLAGS_INSERT_NO_REPLACE):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ufop\airbnb-data-collection\airbnb_listing.py", line 167, in save
    self.config.connection.conn.rollback()
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'psycopg2.extensions.connection' object has no attribute 'conn'
2023-01-13 23:14:08,877 ERROR   Error
Traceback (most recent call last):
  File "C:\ufop\airbnb-data-collection\airbnb_listing.py", line 157, in save
    self.__insert()
  File "C:\ufop\airbnb-data-collection\airbnb_listing.py", line 314, in __insert
    cur.execute(sql, insert_args)
psycopg2.errors.NumericValueOutOfRange: integer out of range


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\ufop\airbnb-data-collection\airbnb_survey.py", line 445, in search
    self.recurse_quadtree(quadtree_node, median_node, None, flag)
  File "C:\ufop\airbnb-data-collection\airbnb_survey.py", line 506, in recurse_quadtree
    (zoomable, median_leaf) = self.search_node(
                              ^^^^^^^^^^^^^^^^^
  File "C:\ufop\airbnb-data-collection\airbnb_survey.py", line 784, in search_node
    if listing.save(self.config.FLAGS_INSERT_NO_REPLACE):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ufop\airbnb-data-collection\airbnb_listing.py", line 167, in save
    self.config.connection.conn.rollback()
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'psycopg2.extensions.connection' object has no attribute 'conn'
2023-01-13 23:14:40,815 INFO    ======================================================================
2023-01-13 23:14:40,815 INFO    Survey 7, for Ouro Preto
2023-01-13 23:14:40,816 INFO    Searching by bounding box, max_zoom=24
2023-01-13 23:14:40,816 INFO    ----------------------------------------------------------------------
2023-01-13 23:14:40,817 INFO    Rectangle calculated: [-20.2519, -43.4372, -20.5229, -43.7846]
2023-01-13 23:14:40,817 INFO    Searching rectangle: zoom factor = 0, node = []
2023-01-13 23:14:42,334 ERROR   Exception in get_search_page_info_rectangle
Traceback (most recent call last):
  File "C:\ufop\airbnb-data-collection\airbnb_listing.py", line 157, in save
    self.__insert()
  File "C:\ufop\airbnb-data-collection\airbnb_listing.py", line 314, in __insert
    cur.execute(sql, insert_args)
psycopg2.errors.NumericValueOutOfRange: integer out of range


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\ufop\airbnb-data-collection\airbnb_survey.py", line 784, in search_node
    if listing.save(self.config.FLAGS_INSERT_NO_REPLACE):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ufop\airbnb-data-collection\airbnb_listing.py", line 167, in save
    self.config.connection.conn.rollback()
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'psycopg2.extensions.connection' object has no attribute 'conn'
2023-01-13 23:14:42,339 ERROR   Error in recurse_quadtree
Traceback (most recent call last):
  File "C:\ufop\airbnb-data-collection\airbnb_listing.py", line 157, in save
    self.__insert()
  File "C:\ufop\airbnb-data-collection\airbnb_listing.py", line 314, in __insert
    cur.execute(sql, insert_args)
psycopg2.errors.NumericValueOutOfRange: integer out of range


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\ufop\airbnb-data-collection\airbnb_survey.py", line 506, in recurse_quadtree
    (zoomable, median_leaf) = self.search_node(
                              ^^^^^^^^^^^^^^^^^
  File "C:\ufop\airbnb-data-collection\airbnb_survey.py", line 784, in search_node
    if listing.save(self.config.FLAGS_INSERT_NO_REPLACE):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ufop\airbnb-data-collection\airbnb_listing.py", line 167, in save
    self.config.connection.conn.rollback()
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'psycopg2.extensions.connection' object has no attribute 'conn'
2023-01-13 23:14:42,342 ERROR   Error
Traceback (most recent call last):
  File "C:\ufop\airbnb-data-collection\airbnb_listing.py", line 157, in save
    self.__insert()
  File "C:\ufop\airbnb-data-collection\airbnb_listing.py", line 314, in __insert
    cur.execute(sql, insert_args)
psycopg2.errors.NumericValueOutOfRange: integer out of range


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\ufop\airbnb-data-collection\airbnb_survey.py", line 445, in search
    self.recurse_quadtree(quadtree_node, median_node, None, flag)
  File "C:\ufop\airbnb-data-collection\airbnb_survey.py", line 506, in recurse_quadtree
    (zoomable, median_leaf) = self.search_node(
                              ^^^^^^^^^^^^^^^^^
  File "C:\ufop\airbnb-data-collection\airbnb_survey.py", line 784, in search_node
    if listing.save(self.config.FLAGS_INSERT_NO_REPLACE):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ufop\airbnb-data-collection\airbnb_listing.py", line 167, in save
    self.config.connection.conn.rollback()
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'psycopg2.extensions.connection' object has no attribute 'conn'
2023-01-13 23:19:33,292 INFO    ======================================================================
2023-01-13 23:19:33,292 INFO    Survey 7, for Ouro Preto
2023-01-13 23:19:33,292 INFO    Searching by bounding box, max_zoom=24
2023-01-13 23:19:33,293 INFO    ----------------------------------------------------------------------
2023-01-13 23:19:33,293 INFO    Rectangle calculated: [-20.2519, -43.4372, -20.5229, -43.7846]
2023-01-13 23:19:33,293 INFO    Searching rectangle: zoom factor = 0, node = []
2023-01-13 23:19:34,678 ERROR   Exception saving room
2023-01-13 23:19:34,678 ERROR   Exception in get_search_page_info_rectangle
Traceback (most recent call last):
  File "C:\ufop\airbnb-data-collection\airbnb_survey.py", line 784, in search_node
    if listing.save(self.config.FLAGS_INSERT_NO_REPLACE):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ufop\airbnb-data-collection\airbnb_listing.py", line 157, in save
    self.__insert()
  File "C:\ufop\airbnb-data-collection\airbnb_listing.py", line 331, in __insert
    cur.execute(sql, insert_args)
TypeError: not all arguments converted during string formatting
2023-01-13 23:19:34,683 ERROR   TypeError in recurse_quadtree
Traceback (most recent call last):
  File "C:\ufop\airbnb-data-collection\airbnb_survey.py", line 506, in recurse_quadtree
    (zoomable, median_leaf) = self.search_node(
                              ^^^^^^^^^^^^^^^^^
  File "C:\ufop\airbnb-data-collection\airbnb_survey.py", line 784, in search_node
    if listing.save(self.config.FLAGS_INSERT_NO_REPLACE):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ufop\airbnb-data-collection\airbnb_listing.py", line 157, in save
    self.__insert()
  File "C:\ufop\airbnb-data-collection\airbnb_listing.py", line 331, in __insert
    cur.execute(sql, insert_args)
TypeError: not all arguments converted during string formatting
2023-01-13 23:19:34,687 ERROR   ('not all arguments converted during string formatting',)
2023-01-13 23:19:34,687 ERROR   Error
Traceback (most recent call last):
  File "C:\ufop\airbnb-data-collection\airbnb_survey.py", line 445, in search
    self.recurse_quadtree(quadtree_node, median_node, None, flag)
  File "C:\ufop\airbnb-data-collection\airbnb_survey.py", line 506, in recurse_quadtree
    (zoomable, median_leaf) = self.search_node(
                              ^^^^^^^^^^^^^^^^^
  File "C:\ufop\airbnb-data-collection\airbnb_survey.py", line 784, in search_node
    if listing.save(self.config.FLAGS_INSERT_NO_REPLACE):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ufop\airbnb-data-collection\airbnb_listing.py", line 157, in save
    self.__insert()
  File "C:\ufop\airbnb-data-collection\airbnb_listing.py", line 331, in __insert
    cur.execute(sql, insert_args)
TypeError: not all arguments converted during string formatting
2023-01-13 23:20:10,875 INFO    ======================================================================
2023-01-13 23:20:10,876 INFO    Survey 7, for Ouro Preto
2023-01-13 23:20:10,876 INFO    Searching by bounding box, max_zoom=24
2023-01-13 23:20:10,877 INFO    ----------------------------------------------------------------------
2023-01-13 23:20:10,877 INFO    Rectangle calculated: [-20.2519, -43.4372, -20.5229, -43.7846]
2023-01-13 23:20:10,878 INFO    Searching rectangle: zoom factor = 0, node = []
2023-01-13 23:20:12,480 INFO    Room 51978370: insert failed
2023-01-13 23:20:12,483 INFO    Room 40752066: insert failed
2023-01-13 23:20:12,488 INFO    Room 41502392: insert failed
2023-01-13 23:20:12,491 INFO    Room 30403033: insert failed
2023-01-13 23:20:12,532 INFO    Room 54222723: insert failed
2023-01-13 23:20:12,547 INFO    Room 50723507: insert failed
2023-01-13 23:20:12,560 INFO    Room 52024666: insert failed
2023-01-13 23:20:12,564 INFO    Room 47334727: insert failed
2023-01-13 23:20:12,571 INFO    Room 40172480: insert failed
2023-01-13 23:20:12,605 INFO    Page 01 returned 18 listings
2023-01-13 23:20:12,895 WARNING HTTP status 403 from web site: IP address blocked. Waiting 1.0 minutes.
2023-01-13 23:20:51,036 INFO    ======================================================================
2023-01-13 23:20:51,036 INFO    Survey 7, for Ouro Preto
2023-01-13 23:20:51,037 INFO    Searching by bounding box, max_zoom=24
2023-01-13 23:20:51,037 INFO    ----------------------------------------------------------------------
2023-01-13 23:20:51,038 INFO    Rectangle calculated: [-20.2519, -43.4372, -20.5229, -43.7846]
2023-01-13 23:20:51,038 INFO    Searching rectangle: zoom factor = 0, node = []
2023-01-13 23:20:51,765 WARNING HTTP status 403 from web site: IP address blocked. Waiting 1.0 minutes.
2023-01-13 23:21:51,920 WARNING HTTP status 403 from web site: IP address blocked. Waiting 1.0 minutes.
2023-01-13 23:22:56,287 INFO    ======================================================================
2023-01-13 23:22:56,287 INFO    Survey 7, for Ouro Preto
2023-01-13 23:22:56,288 INFO    Searching by bounding box, max_zoom=24
2023-01-13 23:22:56,289 INFO    ----------------------------------------------------------------------
2023-01-13 23:22:56,289 INFO    Rectangle calculated: [-20.2519, -43.4372, -20.5229, -43.7846]
2023-01-13 23:22:56,290 INFO    Searching rectangle: zoom factor = 0, node = []
2023-01-13 23:22:57,440 INFO    Room 758263738755481654: insert failed
2023-01-13 23:22:57,455 INFO    Room 47939876: insert failed
2023-01-13 23:22:57,464 INFO    Room 714323517316563160: insert failed
2023-01-13 23:22:57,476 INFO    Room 51978370: insert failed
2023-01-13 23:22:57,482 INFO    Room 40752066: insert failed
2023-01-13 23:22:57,488 INFO    Room 41502392: insert failed
2023-01-13 23:22:57,493 INFO    Room 30403033: insert failed
2023-01-13 23:22:57,498 INFO    Room 736390796820280107: insert failed
2023-01-13 23:22:57,504 INFO    Room 54222723: insert failed
2023-01-13 23:22:57,509 INFO    Room 740983683035077351: insert failed
2023-01-13 23:22:57,534 INFO    Room 53311842: insert failed
2023-01-13 23:22:57,546 INFO    Room 52024666: insert failed
2023-01-13 23:22:57,562 INFO    Room 47334727: insert failed
2023-01-13 23:22:57,575 INFO    Room 50723507: insert failed
2023-01-13 23:22:57,581 INFO    Room 794011987542751252: insert failed
2023-01-13 23:22:57,587 INFO    Room 40172480: insert failed
2023-01-13 23:22:57,587 INFO    Page 01 returned 18 listings
2023-01-13 23:22:59,406 INFO    Room 42158217: insert failed
2023-01-13 23:22:59,410 INFO    Room 47939876: insert failed
2023-01-13 23:22:59,414 INFO    Room 52024666: insert failed
2023-01-13 23:22:59,418 INFO    Room 51978370: insert failed
2023-01-13 23:22:59,439 INFO    Room 40752066: insert failed
2023-01-13 23:22:59,450 INFO    Room 41502392: insert failed
2023-01-13 23:22:59,459 INFO    Room 30403033: insert failed
2023-01-13 23:22:59,467 INFO    Room 40172480: insert failed
2023-01-13 23:22:59,474 INFO    Room 47334727: insert failed
2023-01-13 23:22:59,480 INFO    Room 54222723: insert failed
2023-01-13 23:22:59,486 INFO    Room 50723507: insert failed
2023-01-13 23:22:59,491 INFO    Room 758263738755481654: insert failed
2023-01-13 23:22:59,505 INFO    Room 42270186: insert failed
2023-01-13 23:22:59,520 INFO    Room 740983683035077351: insert failed
2023-01-13 23:22:59,529 INFO    Room 794011987542751252: insert failed
2023-01-13 23:22:59,537 INFO    Room 714323517316563160: insert failed
2023-01-13 23:22:59,543 INFO    Room 736390796820280107: insert failed
2023-01-13 23:22:59,548 INFO    Room 23413941: insert failed
2023-01-13 23:22:59,549 INFO    Page 02 returned 18 listings
2023-01-13 23:23:00,207 WARNING HTTP status 403 from web site: IP address blocked. Waiting 0.08333333333333333 minutes.
2023-01-13 23:23:06,936 INFO    Room 50240014: insert failed
2023-01-13 23:23:06,942 INFO    Room 780430310985839803: insert failed
2023-01-13 23:23:07,131 INFO    Page 03 returned 18 listings
2023-01-13 23:23:09,144 INFO    Page 04 returned 18 listings
2023-01-13 23:23:11,273 INFO    Page 05 returned 18 listings
2023-01-13 23:23:12,089 WARNING HTTP status 403 from web site: IP address blocked. Waiting 0.08333333333333333 minutes.
2023-01-13 23:23:18,734 INFO    Page 06 returned 18 listings
2023-01-13 23:23:20,508 INFO    Page 07 returned 18 listings
2023-01-13 23:23:22,336 WARNING HTTP status 403 from web site: IP address blocked. Waiting 0.08333333333333333 minutes.
2023-01-13 23:23:29,231 WARNING HTTP status 403 from web site: IP address blocked. Waiting 0.08333333333333333 minutes.
2023-01-13 23:23:37,209 WARNING HTTP status 403 from web site: IP address blocked. Waiting 0.08333333333333333 minutes.
2023-01-13 23:23:46,212 WARNING HTTP status 403 from web site: IP address blocked. Waiting 0.08333333333333333 minutes.
2023-01-13 23:23:55,169 INFO    Page 08 returned 18 listings
2023-01-13 23:23:58,340 WARNING HTTP status 403 from web site: IP address blocked. Waiting 0.08333333333333333 minutes.
2023-01-13 23:24:08,859 INFO    Page 09 returned 00 listings
2023-01-13 23:24:08,864 INFO    Final page of listings for this search
2023-01-13 23:24:08,868 INFO    Results: 9 pages, 108 new rooms
2023-01-13 23:24:08,895 INFO    Finishing survey 7, for Ouro Preto
2023-01-14 08:47:44,404 INFO    Resuming survey - retrieved logged progress
2023-01-14 08:47:44,459 INFO    	room_type=None
2023-01-14 08:47:44,459 INFO    	quadtree node=[]
2023-01-14 08:47:44,460 INFO    	median node=[]
2023-01-14 08:47:44,461 INFO    ======================================================================
2023-01-14 08:47:44,462 INFO    Survey 7, for Ouro Preto
2023-01-14 08:47:44,512 INFO    Searching by bounding box, max_zoom=24
2023-01-14 08:47:44,512 INFO    Restarting incomplete survey
2023-01-14 08:47:44,513 INFO    ----------------------------------------------------------------------
2023-01-14 08:47:44,513 INFO    Rectangle calculated: [-20.2519, -43.4372, -20.5229, -43.7846]
2023-01-14 08:47:44,513 INFO    Searching rectangle: zoom factor = 0, node = []
2023-01-14 08:47:47,425 INFO    Room 52024666: insert failed
2023-01-14 08:47:47,432 INFO    Room 30403033: insert failed
2023-01-14 08:47:47,438 INFO    Room 758263738755481654: insert failed
2023-01-14 08:47:47,444 INFO    Room 51978370: insert failed
2023-01-14 08:47:47,466 INFO    Room 40752066: insert failed
2023-01-14 08:47:47,470 INFO    Room 41502392: insert failed
2023-01-14 08:47:47,492 INFO    Room 714323517316563160: insert failed
2023-01-14 08:47:47,498 INFO    Room 53311842: insert failed
2023-01-14 08:47:47,504 INFO    Room 736390796820280107: insert failed
2023-01-14 08:47:47,509 INFO    Room 762279793881682516: insert failed
2023-01-14 08:47:47,514 INFO    Room 51217390: insert failed
2023-01-14 08:47:47,518 INFO    Room 740983683035077351: insert failed
2023-01-14 08:47:47,522 INFO    Room 50723507: insert failed
2023-01-14 08:47:47,526 INFO    Room 19969297: insert failed
2023-01-14 08:47:47,530 INFO    Room 794011987542751252: insert failed
2023-01-14 08:47:47,540 INFO    Room 565861356820112057: insert failed
2023-01-14 08:47:47,541 INFO    Page 01 returned 18 listings
2023-01-14 08:47:48,708 INFO    Room 30403033: insert failed
2023-01-14 08:47:48,714 INFO    Room 52024666: insert failed
2023-01-14 08:47:48,720 INFO    Room 47939876: insert failed
2023-01-14 08:47:48,724 INFO    Room 51978370: insert failed
2023-01-14 08:47:48,730 INFO    Room 40752066: insert failed
2023-01-14 08:47:48,734 INFO    Room 41502392: insert failed
2023-01-14 08:47:48,737 INFO    Room 758263738755481654: insert failed
2023-01-14 08:47:48,740 INFO    Room 43805080: insert failed
2023-01-14 08:47:48,767 INFO    Room 714323517316563160: insert failed
2023-01-14 08:47:48,772 INFO    Room 736390796820280107: insert failed
2023-01-14 08:47:48,778 INFO    Room 53311842: insert failed
2023-01-14 08:47:48,783 INFO    Room 780430310985839803: insert failed
2023-01-14 08:47:48,790 INFO    Room 51217390: insert failed
2023-01-14 08:47:48,814 INFO    Room 740983683035077351: insert failed
2023-01-14 08:47:48,820 INFO    Room 50723507: insert failed
2023-01-14 08:47:48,826 INFO    Room 802715945382951100: insert failed
2023-01-14 08:47:48,831 INFO    Room 19969297: insert failed
2023-01-14 08:47:48,837 INFO    Room 794011987542751252: insert failed
2023-01-14 08:47:48,838 INFO    Page 02 returned 18 listings
2023-01-14 08:47:49,630 INFO    Room 780430310985839803: insert failed
2023-01-14 08:47:49,635 INFO    Room 54222723: insert failed
2023-01-14 08:47:49,639 INFO    Room 47334727: insert failed
2023-01-14 08:47:49,643 INFO    Room 47940589: insert failed
2023-01-14 08:47:49,648 INFO    Room 18853085: insert failed
2023-01-14 08:47:49,652 INFO    Room 53346940: insert failed
2023-01-14 08:47:49,656 INFO    Room 568273495067211791: insert failed
2023-01-14 08:47:49,660 INFO    Room 50240014: insert failed
2023-01-14 08:47:49,664 INFO    Room 733331917587935642: insert failed
2023-01-14 08:47:49,667 INFO    Room 33718911: insert failed
2023-01-14 08:47:49,670 INFO    Room 42270186: insert failed
2023-01-14 08:47:49,674 INFO    Room 40172480: insert failed
2023-01-14 08:47:49,677 INFO    Room 797293152522244108: insert failed
2023-01-14 08:47:49,683 INFO    Room 559203953750433034: insert failed
2023-01-14 08:47:49,687 INFO    Room 36730592: insert failed
2023-01-14 08:47:49,692 INFO    Room 51558179: insert failed
2023-01-14 08:47:49,696 INFO    Room 775977905610868468: insert failed
2023-01-14 08:47:49,696 INFO    Page 03 returned 18 listings
2023-01-14 08:47:50,691 INFO    Room 54077901: insert failed
2023-01-14 08:47:50,696 INFO    Room 549111162795416217: insert failed
2023-01-14 08:47:50,700 INFO    Room 50435311: insert failed
2023-01-14 08:47:50,704 INFO    Room 604853029409645966: insert failed
2023-01-14 08:47:50,709 INFO    Room 53006155: insert failed
2023-01-14 08:47:50,712 INFO    Room 41976839: insert failed
2023-01-14 08:47:50,717 INFO    Room 758155821012645834: insert failed
2023-01-14 08:47:50,720 INFO    Room 36699717: insert failed
2023-01-14 08:47:50,724 INFO    Room 48265935: insert failed
2023-01-14 08:47:50,728 INFO    Room 47302584: insert failed
2023-01-14 08:47:50,732 INFO    Room 50240017: insert failed
2023-01-14 08:47:50,735 INFO    Room 33575682: insert failed
2023-01-14 08:47:50,740 INFO    Room 42733162: insert failed
2023-01-14 08:47:50,744 INFO    Room 30153255: insert failed
2023-01-14 08:47:50,748 INFO    Room 53126670: insert failed
2023-01-14 08:47:50,751 INFO    Room 570774194989594387: insert failed
2023-01-14 08:47:50,763 INFO    Room 35197814: insert failed
2023-01-14 08:47:50,767 INFO    Room 589737176916164461: insert failed
2023-01-14 08:47:50,767 INFO    Page 04 returned 18 listings
2023-01-14 08:47:50,992 WARNING HTTP status 403 from web site: IP address blocked. Waiting 0.1 minutes.
2023-01-14 08:47:57,612 INFO    Page 05 returned 00 listings
2023-01-14 08:47:57,613 INFO    Final page of listings for this search
2023-01-14 08:47:57,613 INFO    Results: 5 pages, 3 new rooms
2023-01-14 08:47:57,620 INFO    Finishing survey 7, for Ouro Preto
2023-01-14 08:50:42,743 INFO    Resuming survey - retrieved logged progress
2023-01-14 08:50:42,744 INFO    	room_type=None
2023-01-14 08:50:42,744 INFO    	quadtree node=[]
2023-01-14 08:50:42,745 INFO    	median node=[]
2023-01-14 08:50:42,747 INFO    ======================================================================
2023-01-14 08:50:42,747 INFO    Survey 7, for Ouro Preto
2023-01-14 08:50:42,748 INFO    Searching by bounding box, max_zoom=24
2023-01-14 08:50:42,749 INFO    Restarting incomplete survey
2023-01-14 08:50:42,749 INFO    ----------------------------------------------------------------------
2023-01-14 08:50:42,750 INFO    Rectangle calculated: [-20.2519, -43.4372, -20.5229, -43.7846]
2023-01-14 08:50:42,750 INFO    Searching rectangle: zoom factor = 0, node = []
2023-01-14 08:50:43,272 WARNING HTTP status 403 from web site: IP address blocked. Waiting 0.1 minutes.
2023-01-14 08:50:51,410 INFO    Room 52024666: insert failed
2023-01-14 08:50:51,414 INFO    Room 30403033: insert failed
2023-01-14 08:50:51,418 INFO    Room 758263738755481654: insert failed
2023-01-14 08:50:51,425 INFO    Room 51978370: insert failed
2023-01-14 08:50:51,429 INFO    Room 40752066: insert failed
2023-01-14 08:50:51,433 INFO    Room 41502392: insert failed
2023-01-14 08:50:51,439 INFO    Room 43805080: insert failed
2023-01-14 08:50:51,444 INFO    Room 714323517316563160: insert failed
2023-01-14 08:50:51,448 INFO    Room 53311842: insert failed
2023-01-14 08:50:51,453 INFO    Room 736390796820280107: insert failed
2023-01-14 08:50:51,458 INFO    Room 762279793881682516: insert failed
2023-01-14 08:50:51,464 INFO    Room 51217390: insert failed
2023-01-14 08:50:51,469 INFO    Room 740983683035077351: insert failed
2023-01-14 08:50:51,475 INFO    Room 50723507: insert failed
2023-01-14 08:50:51,479 INFO    Room 19969297: insert failed
2023-01-14 08:50:51,483 INFO    Room 794011987542751252: insert failed
2023-01-14 08:50:51,487 INFO    Room 802715945382951100: insert failed
2023-01-14 08:50:51,492 INFO    Room 565861356820112057: insert failed
2023-01-14 08:50:51,492 INFO    Page 01 returned 18 listings
2023-01-14 08:50:52,447 INFO    Room 42158217: insert failed
2023-01-14 08:50:52,452 INFO    Room 47939876: insert failed
2023-01-14 08:50:52,457 INFO    Room 51217390: insert failed
2023-01-14 08:50:52,462 INFO    Room 51978370: insert failed
2023-01-14 08:50:52,467 INFO    Room 40752066: insert failed
2023-01-14 08:50:52,471 INFO    Room 30403033: insert failed
2023-01-14 08:50:52,476 INFO    Room 41502392: insert failed
2023-01-14 08:50:52,480 INFO    Room 23413941: insert failed
2023-01-14 08:50:52,485 INFO    Room 50723507: insert failed
2023-01-14 08:50:52,492 INFO    Room 758263738755481654: insert failed
2023-01-14 08:50:52,498 INFO    Room 714323517316563160: insert failed
2023-01-14 08:50:52,502 INFO    Room 740983683035077351: insert failed
2023-01-14 08:50:52,521 INFO    Room 19969297: insert failed
2023-01-14 08:50:52,526 INFO    Room 802715945382951100: insert failed
2023-01-14 08:50:52,530 INFO    Room 794011987542751252: insert failed
2023-01-14 08:50:52,535 INFO    Room 736390796820280107: insert failed
2023-01-14 08:50:52,540 INFO    Room 565861356820112057: insert failed
2023-01-14 08:50:52,545 INFO    Room 762279793881682516: insert failed
2023-01-14 08:50:52,546 INFO    Page 02 returned 18 listings
2023-01-14 08:50:54,305 INFO    Room 565861356820112057: insert failed
2023-01-14 08:50:54,311 INFO    Room 54222723: insert failed
2023-01-14 08:50:54,315 INFO    Room 47334727: insert failed
2023-01-14 08:50:54,321 INFO    Room 47940589: insert failed
2023-01-14 08:50:54,327 INFO    Room 18853085: insert failed
2023-01-14 08:50:54,332 INFO    Room 53346940: insert failed
2023-01-14 08:50:54,337 INFO    Room 568273495067211791: insert failed
2023-01-14 08:50:54,343 INFO    Room 50240014: insert failed
2023-01-14 08:50:54,347 INFO    Room 733331917587935642: insert failed
2023-01-14 08:50:54,353 INFO    Room 33718911: insert failed
2023-01-14 08:50:54,357 INFO    Room 42270186: insert failed
2023-01-14 08:50:54,363 INFO    Room 40172480: insert failed
2023-01-14 08:50:54,367 INFO    Room 797293152522244108: insert failed
2023-01-14 08:50:54,373 INFO    Room 46589065: insert failed
2023-01-14 08:50:54,378 INFO    Room 559203953750433034: insert failed
2023-01-14 08:50:54,385 INFO    Room 36730592: insert failed
2023-01-14 08:50:54,390 INFO    Room 51558179: insert failed
2023-01-14 08:50:54,394 INFO    Room 775977905610868468: insert failed
2023-01-14 08:50:54,394 INFO    Page 03 returned 18 listings
2023-01-14 08:50:55,647 INFO    Room 54077901: insert failed
2023-01-14 08:50:55,654 INFO    Room 549111162795416217: insert failed
2023-01-14 08:50:55,659 INFO    Room 50435311: insert failed
2023-01-14 08:50:55,665 INFO    Room 604853029409645966: insert failed
2023-01-14 08:50:55,669 INFO    Room 53006155: insert failed
2023-01-14 08:50:55,675 INFO    Room 41976839: insert failed
2023-01-14 08:50:55,681 INFO    Room 758155821012645834: insert failed
2023-01-14 08:50:55,686 INFO    Room 36699717: insert failed
2023-01-14 08:50:55,693 INFO    Room 48265935: insert failed
2023-01-14 08:50:55,698 INFO    Room 47302584: insert failed
2023-01-14 08:50:55,705 INFO    Room 50240017: insert failed
2023-01-14 08:50:55,710 INFO    Room 33575682: insert failed
2023-01-14 08:50:55,715 INFO    Room 42733162: insert failed
2023-01-14 08:50:55,722 INFO    Room 30153255: insert failed
2023-01-14 08:50:55,736 INFO    Room 53126670: insert failed
2023-01-14 08:50:55,756 INFO    Room 570774194989594387: insert failed
2023-01-14 08:50:55,762 INFO    Room 35197814: insert failed
2023-01-14 08:50:55,769 INFO    Room 589737176916164461: insert failed
2023-01-14 08:50:55,769 INFO    Page 04 returned 18 listings
2023-01-14 08:50:57,863 INFO    Room 18094957: insert failed
2023-01-14 08:50:57,868 INFO    Room 763211227208332016: insert failed
2023-01-14 08:50:57,872 INFO    Room 35494295: insert failed
2023-01-14 08:50:57,876 INFO    Room 660249447792679503: insert failed
2023-01-14 08:50:57,882 INFO    Room 45223353: insert failed
2023-01-14 08:50:57,889 INFO    Room 40755011: insert failed
2023-01-14 08:50:57,894 INFO    Room 51859731: insert failed
2023-01-14 08:50:57,898 INFO    Room 714915053893510571: insert failed
2023-01-14 08:50:57,904 INFO    Room 17026884: insert failed
2023-01-14 08:50:57,908 INFO    Room 31055389: insert failed
2023-01-14 08:50:57,912 INFO    Room 44471312: insert failed
2023-01-14 08:50:57,916 INFO    Room 791586073239127334: insert failed
2023-01-14 08:50:57,921 INFO    Room 16844691: insert failed
2023-01-14 08:50:57,927 INFO    Room 752794433692563075: insert failed
2023-01-14 08:50:57,931 INFO    Room 679851881766794884: insert failed
2023-01-14 08:50:57,936 INFO    Room 695525664170314691: insert failed
2023-01-14 08:50:57,940 INFO    Room 763179323570545363: insert failed
2023-01-14 08:50:57,948 INFO    Room 758737561063588273: insert failed
2023-01-14 08:50:57,949 INFO    Page 05 returned 18 listings
2023-01-14 08:50:59,965 INFO    Page 06 returned 00 listings
2023-01-14 08:50:59,966 INFO    Final page of listings for this search
2023-01-14 08:50:59,966 INFO    Results: 6 pages, 0 new rooms
2023-01-14 08:50:59,968 INFO    Finishing survey 7, for Ouro Preto
2023-01-14 10:37:54,146 INFO    Resuming survey - retrieved logged progress
2023-01-14 10:37:54,147 INFO    	room_type=None
2023-01-14 10:37:54,148 INFO    	quadtree node=[]
2023-01-14 10:37:54,148 INFO    	median node=[]
2023-01-14 10:37:54,150 INFO    ======================================================================
2023-01-14 10:37:54,151 INFO    Survey 7, for Ouro Preto
2023-01-14 10:37:54,152 INFO    Searching by bounding box, max_zoom=24
2023-01-14 10:37:54,152 INFO    Restarting incomplete survey
2023-01-14 10:37:54,152 INFO    ----------------------------------------------------------------------
2023-01-14 10:37:54,153 INFO    Rectangle calculated: [-20.2519, -43.4372, -20.5229, -43.7846]
2023-01-14 10:37:54,153 INFO    Searching rectangle: zoom factor = 0, node = []
2023-01-14 10:37:56,456 WARNING HTTP status 403 from web site: IP address blocked. Waiting 0.1 minutes.
2023-01-14 10:38:02,740 WARNING HTTP status 403 from web site: IP address blocked. Waiting 0.1 minutes.
